"""Render a ``MalwareReport`` to GitHub-flavoured markdown.

The renderer is pure-string — no markdown library is pulled in. The layout is
the one a vendor's single-family malware report uses: key findings and the
verdict on the first page, the technical analysis by capability with the
measured tables beside the prose they prove, the ATT&CK table and the
indicators together, and the run's own limitations before the appendices.

Three voices, and every heading says which one is speaking:

* **Measured** — what a tool returned, printed as the tool returned it.
* **Observed in sandbox** — what the sample did while a sandbox watched.
* **Assessed** — what a model concluded: the judge, an analyst, or the report
  model. Printed as the model wrote it; the renderer adds the voice tag, the
  citations and a fixed word for a confidence number around it, and never
  rewrites the words. The one exception is how a network indicator is written
  inside prose — defanged — which changes how a value reads, never which value.

Severity badge convention: text in square brackets (``[CRITICAL]``,
``[HIGH]``, ...). Emoji are intentionally avoided so the output renders
cleanly on terminals, PDFs and ticket systems alike.
"""

from __future__ import annotations

import ipaddress
import re
from collections.abc import Callable, Iterable
from types import SimpleNamespace
from typing import Any
from urllib.parse import urlparse

from maljan.analysis.run_summary import (
    bundle_loss_sentence,
    corpus_held_sentence,
    stage_duration_lines,
)
from maljan.core.logger import logger
from maljan.reporting.defang import ProseDefanger, defang
from maljan.reporting.models import (
    CapabilityCell,
    ConsolidatedIOC,
    MalwareReport,
    ProcessNode,
    RegistryMod,
    SandboxSignature,
    TechnicalSubsection,
)
from maljan.schemas.isr_models import UNVERIFIED_TECHNIQUE_MARKER

# ---------------------------------------------------------------------------
# Voices
# ---------------------------------------------------------------------------

MEASURED = "Measured"
OBSERVED = "Observed in sandbox"
ASSESSED = "Assessed"
JUDGE = "Assessed by the judge"
REPORT_MODEL = "Written by the report model"
GENERATED = "Generated by template"
PER_ROW = "Source per row"
PER_SUBSECTION = "Source per subsection"
REFERENCE = "Reference"

# Every tag a heading may carry. A test reads this and fails any H2 without one.
VOICES: frozenset[str] = frozenset(
    {
        MEASURED,
        OBSERVED,
        ASSESSED,
        JUDGE,
        REPORT_MODEL,
        GENERATED,
        PER_ROW,
        PER_SUBSECTION,
        REFERENCE,
    }
)

# ---------------------------------------------------------------------------
# Confidence in words
# ---------------------------------------------------------------------------

# The word a number reads as. A deterministic reading of the producer's own
# number, printed beside it and never instead of it. Only confidence levels are
# written here; likelihood words belong to the models' prose.
CONFIDENCE_WORDS: tuple[tuple[float, str], ...] = (
    (0.90, "high confidence"),
    (0.70, "moderate-to-high confidence"),
    (0.50, "moderate confidence"),
    (0.30, "low confidence"),
    (0.0, "very low confidence"),
)


def confidence_word(value: float | None) -> str:
    """The fixed word for a confidence number, or ``not assessed`` for none."""
    if value is None:
        return "not assessed"
    rounded = round(float(value), 2)
    for floor, word in CONFIDENCE_WORDS:
        if rounded >= floor:
            return word
    return CONFIDENCE_WORDS[-1][1]


def confidence_phrase(value: float | None, producer: str = "") -> str:
    """``high confidence, 0.92, stated by the judge``: the word, the number, the producer."""
    if value is None:
        return "not assessed"
    said = f"{confidence_word(value)}, {float(value):.2f}"
    return f"{said}, stated by {producer}" if producer else said


# Kill-chain order for the ATT&CK table, reconnaissance to impact.
_TACTIC_ORDER: tuple[str, ...] = (
    "TA0043",
    "TA0042",
    "TA0001",
    "TA0002",
    "TA0003",
    "TA0004",
    "TA0005",
    "TA0006",
    "TA0007",
    "TA0008",
    "TA0009",
    "TA0011",
    "TA0010",
    "TA0040",
)

# What a sandbox signature or a rule has to name to be printed beside the
# anti-analysis prose and the API-resolution prose respectively.
_EVASION_WORDS = ("anti", "evas", "debug", "sandbox", "virtual", "vm")
_RESOLUTION_WORDS = ("hash", "peb", "resolv", "dynamic api")

# Long values are cut outside the IOC table, which never cuts one.
_CELL_LIMIT = 240

_EV_RE = re.compile(r"\bev_\d+\b")

# The tools whose ledger entries are a sandbox's.
_SANDBOX_TOOLS = ("sandbox_", "pcap_summary")

# Network indicator kinds, which the IOC section prints in its second table.
_NETWORK_KINDS = frozenset({"domain", "ip", "url", "user_agent", "ja3", "ja3s", "email", "sni"})

# The reputation tools a triage pack may call about the sample itself.
_REPUTATION_TOOLS = ("get_file_report", "check_hash", "file_report", "hash_lookup")
_REPUTATION_KEYS = (
    "malicious",
    "suspicious",
    "harmless",
    "undetected",
    "positives",
    "total",
    "popular_threat_label",
    "suggested_threat_label",
)

# What a sentence of the model's prose is said to rest on when it cites nothing.
_NO_CITATION = "_(no evidence cited)_"
_UNCITED_NOTE = (
    "_Written by the report model with no evidence cited; check it against the "
    "measured sections before quoting it._"
)


class MarkdownRenderer:
    """Render a complete ``MalwareReport`` as a single markdown string."""

    # Section order is kept in one place; each ``_section_*`` call returns
    # a block with one heading and its subsections, or "" when it has nothing.

    def render(self, report: MalwareReport) -> str:
        # Each section is wrapped in _safe_section so a single malformed
        # subtree cannot 500 the whole ``/reports/{id}/markdown`` endpoint.
        ctx = _Context.of(report)
        sections: list[str] = [
            self._safe_section("title", lambda: self._section_title(report, ctx)),
            self._safe_section("key_findings", lambda: self._section_key_findings(report, ctx)),
            self._safe_section("sample_overview", lambda: self._section_overview(report, ctx)),
            self._safe_section("verdict", lambda: self._section_verdict(report, ctx)),
            self._safe_section("execution_flow", lambda: self._section_flow(report, ctx)),
            self._safe_section("technical_analysis", lambda: self._section_technical(report, ctx)),
            self._safe_section("observed_behaviour", lambda: self._section_observed(report, ctx)),
            self._safe_section("static_properties", lambda: self._section_static(report, ctx)),
            self._safe_section("attack_mapping", lambda: self._section_attack(report, ctx)),
            self._safe_section("indicators", lambda: self._section_indicators(report, ctx)),
            self._safe_section("detection", lambda: self._section_detection(report, ctx)),
            self._safe_section(
                "recommendations", lambda: self._section_recommendations(report, ctx)
            ),
            self._safe_section("attribution", lambda: self._section_attribution(report, ctx)),
            self._safe_section("limitations", lambda: self._section_limitations(report, ctx)),
            self._safe_section("appendix_evidence", lambda: self._appendix_evidence(report, ctx)),
            self._safe_section("appendix_run_summary", lambda: self._appendix_run(report)),
            self._safe_section("appendix_references", lambda: self._appendix_references(report)),
            self._safe_section("appendix_methodology", lambda: self._appendix_method(report, ctx)),
        ]
        return "\n\n".join(s.rstrip() for s in sections if s).rstrip() + "\n"

    @staticmethod
    def _safe_section(name: str, fn: Callable[[], str]) -> str:
        """Run a section renderer, return a stub on failure."""
        try:
            return fn()
        except Exception:  # noqa: BLE001 — markdown is non-critical UX surface
            logger.exception("markdown_renderer: section '%s' raised; substituting stub.", name)
            return f"<!-- section '{name}' rendering failed — see server logs -->"

    # ------------------------------------------------------------------
    # 0. Title block
    # ------------------------------------------------------------------

    def _section_title(self, report: MalwareReport, ctx: _Context) -> str:
        ident = report.identity
        sha256 = ident.hashes.sha256 or "unknown"
        lines = [f"# {report_title(report)}", ""]
        fm = report.front_matter
        if fm is not None:
            parts = [f"**TLP:{fm.tlp}**"]
            if fm.report_number:
                parts.append(f"Report {fm.report_number}")
            parts.append(fm.report_date or report.generated_at.date().isoformat())
            parts.append(f"{fm.publisher} report version {fm.version}")
            lines.append(" · ".join(parts) + "  ")
        else:
            lines.append(f"Generated {report.generated_at.isoformat()}  ")
        lines.append(
            f"**Sample:** `{sha256}` ({ident.file_type}, {ident.file_size_bytes:,} bytes)  "
        )
        lines.append(_verdict_line(report))
        for row in ctx.verdict_findings:
            lines.append(
                f"  \n_Unresolved on the verdict: `{row['code']}`: {_one_line(row['message'])}_"
            )

        if report.overall_confidence is None:
            lines.append(
                "\n> **[NO CONFIDENCE ASSESSED]** This verdict carries no "
                "confidence: the judge assessed none, or never answered at all. "
                "Nothing is substituted for one — the analysts' confidence "
                "belongs to their own claims, and a verdict none of them reached "
                "is not something they rated."
            )
        if report.degraded_mode:
            reasons = "; ".join(report.degradation_reasons) or "low analyst/sandbox data"
            lines.append(
                "\n> **[DEGRADED RUN]** This analysis ran with limited data, so the "
                "verdict, confidence and severity below should be treated as tentative "
                f"and corroborated manually.  \n> Reasons: {reasons}"
            )
        elif report.degradation_reasons:
            lines.append("\n**Notes**: " + "; ".join(report.degradation_reasons) + ".")

        evidence = (report.run_summary or {}).get("evidence") or {}
        entries = evidence.get("entries")
        if entries:
            failed = int(evidence.get("failed") or 0)
            said = f"\nEvidence: {entries} tool call(s)"
            said += f", {failed} failed" if failed else ""
            lines.append(said + " (see §13).")
        profile = (report.run_summary or {}).get("profile") or {}
        # A reduced profile changes what evidence backs the verdict, so a
        # non-default one is named; the default keeps the block unchanged.
        if profile.get("name") and profile["name"] != "default":
            analysts = profile.get("analysts") or []
            custom = set(profile.get("custom") or [])
            names = ", ".join(f"{a} (custom)" if a in custom else a for a in analysts)
            lines.append(f"\nProfile: {profile['name']} — analysts: {names}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 1. Key findings
    # ------------------------------------------------------------------

    def _section_key_findings(self, report: MalwareReport, ctx: _Context) -> str:
        lines = [_heading(1, "Key findings", REPORT_MODEL), ""]
        for finding in report.key_findings:
            lines.append(f"- {ctx.line(finding.text)} {_cite(finding.evidence_ids)}")
        summary = report.executive_summary.strip()
        if summary:
            if report.key_findings:
                lines.append("")
            lines.append(ctx.prose(summary))
            if not report.key_findings and not _EV_RE.search(summary):
                lines.extend(["", _UNCITED_NOTE])
            return "\n".join(lines)
        if report.key_findings:
            return "\n".join(lines)

        # No summary was written. Said, with the reason, and the verdict's
        # facts listed by the platform with the voice of each.
        why = next(
            (
                reason
                for reason in report.degradation_reasons
                if reason.startswith(_NO_SUMMARY_PREFIX)
            ),
            "",
        )
        reason = why.split(":", 1)[1].strip() if ":" in why else "the report model wrote none"
        lines.append(f"No summary was written: {reason}.")
        if any(r in _INCONCLUSIVE for r in report.degradation_reasons):
            lines.extend(
                [
                    "",
                    "This analysis is inconclusive: nothing about the sample was "
                    "established, and the verdict below is not a finding about it.",
                ]
            )
        lines.append("")
        lines.append(f"- Verdict: {_verdict_words(report)} _({JUDGE})_")
        family = report.attribution.family
        voice = OBSERVED if report.attribution.family_source == "sandbox" else JUDGE
        lines.append(f"- Family: {_one_line(family or 'none attributed')} _({voice})_")
        top = sorted(report.ttp_mappings, key=lambda m: -m.confidence)[:3]
        if top:
            named = ", ".join(f"{m.technique_id} {m.technique_name}" for m in top)
            lines.append(f"- Top published techniques: {named} _({ASSESSED})_")
        published = sum(
            1 for row in ctx.iocs if row.kind in _NETWORK_KINDS and row.published == "yes"
        )
        lines.append(f"- Published network indicators: {published} _({MEASURED})_")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 2. Sample overview
    # ------------------------------------------------------------------

    def _section_overview(self, report: MalwareReport, ctx: _Context) -> str:
        ident = report.identity
        hashes = ident.hashes
        lines = [_heading(2, "Sample overview", MEASURED), ""]
        lines.append(_row("Field", "Value"))
        lines.append(_divider(2))
        lines.append(_row("File name (as submitted)", f"`{ident.file_name or 'unknown'}`"))
        lines.append(_row("Size", f"{ident.file_size_bytes:,} bytes"))
        kind = ident.file_type
        if ident.architecture:
            kind += f", {ident.architecture}"
        if ident.is_dll is not None:
            kind += ", DLL" if ident.is_dll else ", executable"
        lines.append(_row("Type", kind))
        name = (ident.file_name or "").lower()
        if ident.is_dll and name.endswith(".exe"):
            lines.append(_row("Name and type", "a DLL submitted under an .exe name"))
        if ident.mime_type:
            lines.append(_row("MIME", ident.mime_type))
        if ident.magic_bytes:
            lines.append(_row("Magic bytes", f"`{ident.magic_bytes}`"))
        if ident.compile_timestamp:
            lines.append(
                _row(
                    "Compile timestamp",
                    f"{ident.compile_timestamp.isoformat()} (header value; can be forged)",
                )
            )
        if ident.language_or_compiler:
            lines.append(_row("Compiler / language", ident.language_or_compiler))
        if ident.export_name:
            lines.append(_row("Export directory name", f"`{ident.export_name}`"))
        if ident.internal_name:
            lines.append(_row("Internal name", f"`{ident.internal_name}`"))
        signing = ident.signing
        cited = f" ({signing.evidence_id})" if signing.evidence_id else ""
        lines.append(_row("Signed", f"{'yes' if signing.is_signed else 'no'}{cited}"))
        if signing.signer_subject:
            lines.append(_row("Signer", signing.signer_subject))
        if signing.signer_issuer:
            lines.append(_row("Signer issuer", signing.signer_issuer))
        if signing.signature_valid is not None:
            lines.append(_row("Signature chain", "valid" if signing.signature_valid else "invalid"))
        static = report.static
        if static is not None and (static.packer_matches or static.packer_hint):
            names = ", ".join(str(m.get("name") or "?") for m in static.packer_matches[:4])
            lines.append(_row("Packer signatures", names or static.packer_hint))
        lines.append(_row("Reputation", _reputation_line(report)))
        lines.append(_row("Report generated", report.generated_at.isoformat()))
        lines.append("")
        lines.append(_row("Algorithm", "Value"))
        lines.append(_divider(2))
        for algo, value in (
            ("MD5", hashes.md5),
            ("SHA-1", hashes.sha1),
            ("SHA-256", hashes.sha256),
            ("SHA-512", hashes.sha512),
            ("imphash", hashes.imphash),
            ("ssdeep", hashes.ssdeep),
            ("TLSH", hashes.tlsh),
        ):
            if value:
                lines.append(_row(algo, f"`{value}`"))
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 3. Verdict and assessment
    # ------------------------------------------------------------------

    def _section_verdict(self, report: MalwareReport, ctx: _Context) -> str:
        lines = [_heading(3, "Verdict and assessment", JUDGE), ""]
        lines.append(f"**Verdict:** {_verdict_words(report)}")
        severity = report.severity
        if severity is None:
            # Said, not defaulted: "Informational" for a rating nobody gave
            # tells a reader something the run never established.
            lines.extend(
                ["", "**Severity:** not assessed — the judge produced no severity rating."]
            )
        else:
            lines.extend(["", f"**Severity:** `[{severity.rating.upper()}]`"])
            if severity.business_impact:
                lines.extend(["", "**Why, in the judge's words:**", ""])
                quoted = ctx.prose(severity.business_impact).splitlines()
                lines.extend(f"> {line}" if line.strip() else ">" for line in quoted)
            if severity.affected_platforms:
                lines.extend(
                    ["", "**Affected platforms:** " + ", ".join(severity.affected_platforms)]
                )
            if severity.likely_targets:
                lines.extend(["", "**Likely targets:** " + ", ".join(severity.likely_targets)])
        if report.malware_category and str(report.malware_category).lower() != "unknown":
            lines.extend(
                [
                    "",
                    f"**Category:** {_one_line(report.malware_category)} "
                    "_(a behavioural class, not a family)_",
                ]
            )
        lines.extend(["", "**Family:** " + _family_words(report)])
        conclusion = report.conclusion
        if conclusion is not None and conclusion.sophistication_rating:
            lines.extend(
                ["", f"**Sophistication:** {conclusion.sophistication_rating} _({REPORT_MODEL})_"]
            )
        negotiation = (report.run_summary or {}).get("negotiation") or report.negotiation_summary
        if isinstance(negotiation, dict) and negotiation.get("rounds_completed") is not None:
            rounds = negotiation.get("rounds_completed")
            reason = str(negotiation.get("termination_reason") or "").strip()
            said = (
                f"the analysts reached consensus after {rounds} round(s)"
                if reason == "consensus"
                else f"the negotiation ended after {rounds} round(s)"
                + (f" ({reason})" if reason and reason != "unknown" else "")
            )
            lines.extend(["", f"**Analyst agreement:** {said} _({MEASURED})_."])
        if ctx.verdict_findings:
            lines.extend(["", "**Unresolved findings on the verdict:**", ""])
            lines.extend(
                f"- `{row['code']}`: {_one_line(row['message'])}" for row in ctx.verdict_findings
            )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 4. Execution flow
    # ------------------------------------------------------------------

    def _section_flow(self, report: MalwareReport, ctx: _Context) -> str:
        ta = report.technical_analysis
        steps = list(ta.execution_flow) if ta is not None else []
        if not steps:
            return ""
        lines = [_heading(4, "Execution flow", REPORT_MODEL), ""]
        lines.append(
            "_Each step is marked as the report model marked it: observed in the "
            "sandbox, or assessed from the code and the analysts' claims._"
        )
        lines.append("")
        for index, step in enumerate(sorted(steps, key=lambda s: s.order), start=1):
            mark = "observed in sandbox" if step.voice == "observed" else "assessed"
            note = (
                " _(unresolved: report.flow_voice)_" if str(step.order) in ctx.flow_findings else ""
            )
            lines.append(
                f"{index}. {ctx.line(step.action)} ({mark}) {_cite(step.evidence_refs)}{note}"
            )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 5. Technical analysis
    # ------------------------------------------------------------------

    def _section_technical(self, report: MalwareReport, ctx: _Context) -> str:
        ta = report.technical_analysis
        static = report.static
        dynamic = report.dynamic
        blocks: list[str] = []

        if report.capabilities_narrative:
            # A report stored before the composer wrote these subsections
            # carries the old capability paragraphs; they are printed here,
            # under the analysis's lead-in, rather than lost.
            body = [_subheading("", "Overview", REPORT_MODEL), ""]
            for paragraph in report.capabilities_narrative:
                body.extend([ctx.prose(paragraph.strip()), ""])
            body.append(_UNCITED_NOTE)
            blocks.append("\n".join(body))

        # 5.1 Packing, obfuscation and anti-analysis.
        measured: list[str] = []
        if static is not None and static.sections:
            entropies = ", ".join(
                f"`{_one_line(sec.name)}` {sec.entropy:.2f}"
                + (" [HIGH]" if sec.entropy > 7.0 else "")
                for sec in static.sections
            )
            measured.append(f"_{MEASURED}:_ section entropy {entropies}.")
        if static is not None and static.packer_matches:
            measured.extend(["", f"_{MEASURED}:_ packer signatures", ""])
            measured.append(_row("Name", "Kind", "Confidence", "Method", "Evidence"))
            measured.append(_divider(5))
            for pm in static.packer_matches[:6]:
                evidence = ", ".join(f"`{e}`" for e in (pm.get("evidence") or [])[:4])
                measured.append(
                    _row(
                        pm.get("name") or "?",
                        pm.get("kind") or "-",
                        f"{float(pm.get('confidence') or 0.0):.2f}",
                        pm.get("method") or "-",
                        evidence or "-",
                    )
                )
        elif static is not None and static.packer_hint:
            measured.append(f"_{MEASURED}:_ packer hint {static.packer_hint}.")
        evasive = [
            sig
            for sig in (dynamic.sandbox_signatures if dynamic else [])
            if _names_any(sig.name + " " + sig.description, _EVASION_WORDS)
        ]
        if evasive:
            measured.extend(["", f"_{OBSERVED}:_ evasion signatures", ""])
            measured.append(_row("Name", "Severity", "Description"))
            measured.append(_divider(3))
            for sig in evasive[:10]:
                measured.append(
                    _row(sig.name, sig.severity, _truncate(sig.description, _CELL_LIMIT))
                )
        blocks.append(
            _subsection(
                "5.1",
                "Packing, obfuscation and anti-analysis",
                [ta.packing_obfuscation, ta.evasion_antiforensics] if ta else [],
                measured,
                ctx,
            )
        )

        # 5.2 API and string resolution.
        measured = []
        if static is not None and static.imports:
            libraries = {row.dll.lower() for row in static.imports if row.dll}
            measured.append(
                f"_{MEASURED}:_ {len(static.imports)} static imports from "
                f"{len(libraries)} librar{'y' if len(libraries) == 1 else 'ies'}."
            )
        resolving = [
            hit
            for hit in (static.api_technique_hits if static else [])
            if _names_any(str(hit.get("name") or ""), _RESOLUTION_WORDS)
        ]
        if resolving:
            names = ", ".join(f"{h.get('name')} ({h.get('source')})" for h in resolving[:8])
            measured.append(f"_{MEASURED}:_ rule hits {names}.")
        blocks.append(
            _subsection(
                "5.2",
                "API and string resolution",
                [ta.string_resolution] if ta else [],
                measured,
                ctx,
            )
        )

        # 5.3 Configuration.
        if ta is not None and ta.configuration:
            body = [_subheading("5.3", "Configuration", REPORT_MODEL), ""]
            body.append(_row("Key", "Value", "How obtained", "Evidence"))
            body.append(_divider(4))
            for index, item in enumerate(ta.configuration):
                unresolved = index + 1 in ctx.config_findings
                how = item.how_obtained + (
                    " (unresolved: report.configuration_uncited)" if unresolved else ""
                )
                body.append(
                    _row(
                        ctx.cell(item.key),
                        ctx.cell(item.value),
                        how,
                        ", ".join(item.evidence_refs) or "no evidence cited",
                    )
                )
            blocks.append("\n".join(body))

        # 5.4 Persistence.
        measured = []
        if report.persistence:
            measured.append(f"_{PER_ROW}:_ persistence mechanisms")
            measured.append("")
            measured.append(_row("Kind", "Target", "Payload", "Technique", "Evidence"))
            measured.append(_divider(5))
            for mech in report.persistence[:40]:
                measured.append(
                    _row(
                        mech.kind,
                        f"`{_truncate(mech.target, _CELL_LIMIT)}`",
                        f"`{_truncate(mech.payload, _CELL_LIMIT)}`" if mech.payload else "-",
                        mech.technique_id or "-",
                        mech.evidence_ref or "-",
                    )
                )
        elif ctx.sandbox_ran:
            measured.append(f"_{OBSERVED}:_ no persistence observed." + ctx.partial_sentence())
        blocks.append(
            _subsection("5.4", "Persistence", [ta.persistence_detail] if ta else [], measured, ctx)
        )

        # 5.5 Discovery.
        measured = []
        commands = [
            node for node in _spawned(dynamic.process_tree if dynamic else []) if node.command_line
        ]
        if commands:
            measured.extend([f"_{OBSERVED}:_ commands the sample started", ""])
            measured.append(_row("PID", "Command line"))
            measured.append(_divider(2))
            for node in commands[:20]:
                measured.append(_row(node.pid, f"`{_truncate(node.command_line, _CELL_LIMIT)}`"))
        blocks.append(_subsection("5.5", "Discovery", [ta.discovery] if ta else [], measured, ctx))

        # 5.6 Commands and capabilities.
        if ta is not None and (ta.commands or ta.cli_flags):
            body = [_subheading("5.6", "Commands and capabilities", REPORT_MODEL), ""]
            if ta.commands:
                body.append(_row("ID", "Command", "Description", "Evidence"))
                body.append(_divider(4))
                for cmd in ta.commands:
                    body.append(
                        _row(
                            ctx.cell(cmd.id or "-"),
                            ctx.cell(cmd.name),
                            ctx.cell(cmd.description or "-"),
                            ", ".join(cmd.evidence_refs) or "no evidence cited",
                        )
                    )
                body.append("")
            if ta.cli_flags:
                body.append("Command-line flags:")
                body.append("")
                body.append(_row("Flag", "Meaning", "Evidence"))
                body.append(_divider(3))
                for flag in ta.cli_flags[:20]:
                    body.append(
                        _row(
                            f"`{flag.flag}`",
                            ctx.cell(flag.description or "-"),
                            flag.evidence_ref or "no evidence cited",
                        )
                    )
            blocks.append("\n".join(body).rstrip())

        # 5.7 Command and control.
        measured = []
        if report.c2_channels:
            measured.extend([f"_{REPORT_MODEL}:_ channels", ""])
            measured.append(
                _row(
                    "Channel",
                    "Protocol",
                    "Endpoint(s)",
                    "Encryption",
                    "Beacon/packet format",
                    "Evidence",
                )
            )
            measured.append(_divider(6))
            for ch in report.c2_channels[:10]:
                fmt = " / ".join(part for part in (ch.beacon_format, ch.packet_layout) if part)
                refs = list(ch.evidence_refs) + ([ch.evidence_ref] if ch.evidence_ref else [])
                measured.append(
                    _row(
                        ctx.cell(ch.name),
                        ctx.cell(ch.protocol or "-"),
                        "; ".join(_endpoint(e) for e in ch.endpoints) or "-",
                        ctx.cell(ch.encryption or "-"),
                        ctx.cell(fmt or "-"),
                        ", ".join(dict.fromkeys(refs)) or "no evidence cited",
                    )
                )
        net = report.network
        observed_urls = [u for u in (net.urls if net else []) if u.source == "sandbox"]
        if observed_urls:
            measured.extend(["", f"_{OBSERVED}:_ requests", ""])
            measured.append(_row("Method", "URL", "Status", "User-Agent"))
            measured.append(_divider(4))
            for u in observed_urls[:20]:
                measured.append(
                    _row(
                        u.method,
                        f"`{defang(_truncate(u.url, _CELL_LIMIT), 'url')}`",
                        u.status or "-",
                        _truncate(u.user_agent or "-", _CELL_LIMIT),
                    )
                )
        if net is not None and (net.ja3_fingerprints or net.ja3s_fingerprints):
            prints = [f"JA3 `{j}`" for j in net.ja3_fingerprints[:6]]
            prints += [f"JA3S `{j}`" for j in net.ja3s_fingerprints[:6]]
            measured.extend(["", f"_{OBSERVED}:_ TLS fingerprints " + ", ".join(prints) + "."])
        prose = [ta.command_and_control, ta.message_packet_structure] if ta else []
        blocks.append(_subsection("5.7", "Command and control", prose, measured, ctx))

        # 5.8 Payloads and dropped files.
        measured = []
        carved = [r for r in (static.embedded_resources if static else []) if r.get("carved")]
        dropped = [
            op
            for op in (dynamic.file_operations if dynamic else [])
            if isinstance(op, dict) and op.get("operation") == "write"
        ]
        if carved or dropped:
            measured.extend([f"_{PER_ROW}:_ payloads", ""])
            measured.append(_row("Name/offset", "Size", "SHA-256", "Type", "Source"))
            measured.append(_divider(5))
            for res in carved[:10]:
                measured.append(
                    _row(
                        f"`{res.get('id') or '?'}` ({res.get('source') or '-'})",
                        f"{res.get('size', 0)} bytes",
                        f"`{str(res.get('sha256') or '-').lower()}`",
                        res.get("type") or "?",
                        "carved (static)",
                    )
                )
            for op in dropped[:20]:
                measured.append(
                    _row(
                        f"`{_truncate(str(op.get('path') or op.get('name') or '?'), _CELL_LIMIT)}`",
                        f"{op['size']} bytes" if op.get("size") else "-",
                        f"`{str(op.get('sha256')).lower()}`" if op.get("sha256") else "-",
                        op.get("type") or "-",
                        "dropped (sandbox)",
                    )
                )
        blocks.append(
            _subsection(
                "5.8", "Payloads and dropped files", [ta.payloads] if ta else [], measured, ctx
            )
        )

        # 5.9 Family-specific behaviour.
        if ta is not None:
            blocks.append(_ransomware_block(ta, ctx))

        body = [block for block in blocks if block]
        if not body:
            return ""
        return "\n\n".join([_heading(5, "Technical analysis", PER_SUBSECTION), *body])

    # ------------------------------------------------------------------
    # 6. Observed behaviour
    # ------------------------------------------------------------------

    def _section_observed(self, report: MalwareReport, ctx: _Context) -> str:
        dyn = report.dynamic
        lines = [_heading(6, "Observed behaviour", OBSERVED), ""]
        if dyn is None and not ctx.sandbox_ran:
            reason = next(
                (r for r in report.degradation_reasons if "sandbox" in r.lower()),
                "no sandbox tool was called in this run"
                if ctx.sandbox_known
                else "this report does not record whether a sandbox ran",
            )
            lines.append(f"Not run in a sandbox: {reason}.")
            return "\n".join(lines)
        lines.append(_environment_line(report))
        lines.append("")
        if dyn is None:
            lines.append("The sandbox recorded no behaviour." + ctx.partial_sentence())
            return "\n".join(lines)
        if dyn.unavailable:
            names = ", ".join(f"`{name}`" for name in dyn.unavailable)
            lines.extend([f"_Not provided by this sandbox: {names}._", ""])

        if dyn.process_tree:
            lines.extend(["### 6.1 Process tree", "", "```"])
            for root in dyn.process_tree:
                lines.extend(_process_tree_lines(root, 0))
            lines.extend(["```", ""])

        files = [op for op in dyn.file_operations if isinstance(op, dict) and op.get("path")]
        if files:
            lines.extend(
                ["### 6.2 File operations", "", _row("Path", "Operation", "API"), _divider(3)]
            )
            for op in files[:40]:
                lines.append(
                    _row(
                        f"`{_truncate(str(op.get('path', '')), _CELL_LIMIT)}`",
                        op.get("operation", "-"),
                        op.get("api", "-"),
                    )
                )
            lines.append("")

        if dyn.registry_mods:
            lines.extend(
                [
                    "### 6.3 Registry modifications",
                    "",
                    _row("Hive", "Key", "Value", "Operation"),
                    _divider(4),
                ]
            )
            lines.extend(_registry_row(reg) for reg in dyn.registry_mods[:40])
            lines.append("")

        mutexes = [
            str(op.get("name"))
            for op in dyn.file_operations
            if isinstance(op, dict) and op.get("operation") == "mutex" and op.get("name")
        ]
        if mutexes:
            lines.extend(["### 6.4 Mutexes", ""])
            lines.extend(f"- `{_one_line(name)}`" for name in mutexes[:40])
            lines.append("")

        services = next((s for s in report.sections if s.key == "sandbox_services_and_tasks"), None)
        if services is not None and services.rows:
            lines.extend(["### 6.5 Services and tasks", ""])
            lines.extend(_evidence_rows(services, ctx.prose))
            if services.evidence_ids:
                lines.extend(["", f"_Evidence: {', '.join(services.evidence_ids)}_"])
            lines.append("")

        if dyn.notable_apis:
            lines.extend(["### 6.6 Notable APIs", "", _row("API", "Process", "Count"), _divider(3)])
            for api in dyn.notable_apis[:20]:
                if isinstance(api, dict):
                    lines.append(
                        _row(
                            f"`{api.get('api', '-')}`",
                            f"`{api.get('process') or '-'}`",
                            api.get("count", 0),
                        )
                    )
            lines.append("")

        if dyn.sandbox_signatures:
            lines.extend(
                [
                    "### 6.7 Sandbox signatures",
                    "",
                    _row("Name", "Severity", "Techniques", "Description"),
                    _divider(4),
                ]
            )
            lines.extend(_signature_row(sig) for sig in dyn.sandbox_signatures[:30])
            lines.append("")

        if len(lines) <= 4:
            lines.append("The sandbox ran and recorded little." + ctx.partial_sentence())
        return "\n".join(lines).rstrip()

    # ------------------------------------------------------------------
    # 7. Static properties
    # ------------------------------------------------------------------

    def _section_static(self, report: MalwareReport, ctx: _Context) -> str:
        static = report.static
        if static is None:
            return ""
        lines = [_heading(7, "Static properties", MEASURED), ""]

        if static.sections:
            lines.extend(["### 7.1 Sections", ""])
            lines.append(_row("Name", "VA", "VSize", "Raw offset", "Raw size", "Entropy", "Flags"))
            lines.append(_divider(7))
            for sec in static.sections:
                flag = "[HIGH ENTROPY]" if sec.entropy > 7.0 else ""
                if sec.is_suspicious and not flag:
                    flag = "[SUSPICIOUS]"
                lines.append(
                    _row(
                        f"`{sec.name}`",
                        sec.virtual_address,
                        sec.virtual_size,
                        f"0x{sec.raw_offset:x}",
                        sec.raw_size,
                        f"{sec.entropy:.2f}",
                        " ".join(part for part in (sec.characteristics, flag) if part) or "-",
                    )
                )
            lines.append("")

        if static.imports or static.api_capabilities:
            lines.extend(["### 7.2 Imports", ""])
            by_dll: dict[str, list[str]] = {}
            for row in static.imports:
                by_dll.setdefault(row.dll or "?", []).append(row.function)
            if by_dll:
                lines.append(_row("Library", "Functions"))
                lines.append(_divider(2))
                for dll, functions in list(by_dll.items())[:40]:
                    shown = ", ".join(f"`{f}`" for f in functions[:12])
                    more = f" and {len(functions) - 12} more" if len(functions) > 12 else ""
                    lines.append(_row(f"`{dll}`", shown + more))
                lines.append("")
            if static.api_capabilities:
                ordered = sorted(static.api_capabilities.items(), key=lambda kv: -kv[1])
                cited = ", ".join(static.api_capabilities_evidence_ids)
                rates = static.api_capability_rates

                def _profile(category: str, count: int) -> str:
                    share = rates.get(category)
                    return f"{category} ×{count}" + (
                        f" ({share:.1f}%)" if share is not None else ""
                    )

                lines.append(
                    "**Import capability profile**"
                    + (f" ({cited})" if cited else "")
                    + ": "
                    + ", ".join(_profile(cat, count) for cat, count in ordered)
                )
                if static.api_capability_corpus:
                    lines.extend(
                        [
                            "",
                            "_The bracketed share is how much of "
                            f"{static.api_capability_corpus} the category appears on; it says "
                            "nothing about how likely this sample is to be benign._",
                        ]
                    )
                lines.append("")

        if static.export_rows or static.exports:
            lines.extend(["### 7.3 Exports", ""])
            lines.append(_row("Name", "Ordinal", "RVA"))
            lines.append(_divider(3))
            if static.export_rows:
                for exp in static.export_rows[:60]:
                    lines.append(
                        _row(f"`{exp.name or '(unnamed)'}`", exp.ordinal or "-", exp.rva or "-")
                    )
                rvas = [exp.rva for exp in static.export_rows if exp.rva]
                if len(rvas) > 1 and len(set(rvas)) == 1:
                    lines.extend(["", f"All {len(rvas)} exports share one address, {rvas[0]}."])
            else:
                for name in static.exports[:60]:
                    lines.append(_row(f"`{name}`", "-", "-"))
            lines.append("")

        if static.embedded_resources:
            plain = [r for r in static.embedded_resources if not r.get("carved")]
            if plain:
                lines.extend(["### 7.4 Resources", ""])
                for res in plain[:20]:
                    kind = res.get("type") or res.get("kind") or "resource"
                    size = res.get("size")
                    lines.append(f"- {kind}" + (f" ({size} bytes)" if size else ""))
                lines.append("")

        rules = [s for s in report.sections if s.key in _RULE_SECTIONS]
        if rules:
            lines.extend(["### 7.5 Rule hits", ""])
            for section in rules:
                lines.extend([f"{section.title}:", ""])
                lines.extend(_evidence_rows(section, ctx.prose))
                if section.evidence_ids:
                    lines.extend(["", f"_Evidence: {', '.join(section.evidence_ids)}_"])
                lines.append("")

        if static.interesting_strings:
            lines.extend(["### 7.6 Strings of note", ""])
            lines.append(
                "_Values extracted from the file's bytes, printed as they are. A "
                "network-looking string is not an observed endpoint._"
            )
            lines.append("")
            answers = {(row.kind, row.value.lower()): row.published for row in ctx.iocs}
            lines.append(_row("Value", "Kind", "Notes", "Published"))
            lines.append(_divider(4))
            for ioc in static.interesting_strings[:60]:
                published = answers.get((ioc.kind, ioc.value.strip().lower())) or "-"
                lines.append(
                    _row(
                        f"`{_truncate(ioc.value, _CELL_LIMIT)}`",
                        ioc.kind,
                        ioc.notes or "-",
                        published,
                    )
                )
            lines.append("")

        if static.pdb_path:
            lines.extend([f"Debug PDB path: `{static.pdb_path}`", ""])
        if static.obfuscation_indicators:
            lines.append("Obfuscation indicators: " + ", ".join(static.obfuscation_indicators))
        return "\n".join(lines).rstrip()

    # ------------------------------------------------------------------
    # 8. MITRE ATT&CK mapping
    # ------------------------------------------------------------------

    def _section_attack(self, report: MalwareReport, ctx: _Context) -> str:
        cells = list(report.capability_matrix)
        lines = [_heading(8, "MITRE ATT&CK mapping", PER_ROW), ""]
        mappings = {m.technique_id: m for m in report.ttp_mappings}
        hits = list(report.static.api_technique_hits) if report.static else []
        if not cells and not mappings and not hits:
            lines.append("_No ATT&CK techniques mapped._")
            return "\n".join(
                lines + _not_published_lines(report) + _unmapped_behaviour_lines(report)
            )

        corroboration = (report.run_summary or {}).get("corroboration") or {}
        lines.append(
            _row(
                "Tactic",
                "ID",
                "Technique",
                "Procedure",
                "Source",
                "Confidence",
                "Status",
                "Evidence",
            )
        )
        lines.append(_divider(8))
        seen: set[str] = set()
        for cell in sorted(cells, key=_tactic_key):
            seen.add(cell.technique_id)
            lines.append(_attack_row(cell, mappings.get(cell.technique_id), corroboration, ctx))
        # A published technique the matrix does not hold — a stored report
        # from before every id was collected into it — still gets its row.
        for tid, mapping in mappings.items():
            if tid in seen:
                continue
            lines.append(
                _row(
                    f"{mapping.tactic_name} ({mapping.tactic})"
                    if mapping.tactic
                    else mapping.tactic_name or "-",
                    tid,
                    mapping.technique_name,
                    ctx.cell(_truncate(mapping.evidence_quotes[0], 160))
                    if mapping.evidence_quotes
                    else "-",
                    ", ".join(mapping.contributing_layers) or "-",
                    confidence_phrase(mapping.confidence),
                    "published" + (", corroborated" if mapping.is_corroborated else ""),
                    ", ".join(_ids_in(mapping.evidence_quotes)) or "-",
                )
            )
        # The rules that fired over the import table, by source then
        # technique: a stated order, so a capa-heavy binary cannot push the
        # knowledge table's rows off the end of the audit trail.
        ordered = sorted(
            hits,
            key=lambda h: (
                str(h.get("source") or ""),
                str(h.get("technique_id") or ""),
                str(h.get("rule") or ""),
            ),
        )
        for hit in ordered[:25]:
            lines.append(_import_rule_row(hit, mappings))
        if hits:
            lines.extend(
                [
                    "",
                    "_Rows whose source is `pipeline:` are rules that fired over the import "
                    "table — no sandbox, no model. Their Procedure cell ends with how much "
                    "ordinary software the same rule fires on, over the corpus it names; it "
                    "says nothing about how likely this sample is to be benign, and `not "
                    "measured` means the rule has no measurement, not that it never fires._",
                ]
            )
        return "\n".join(
            lines + _not_published_lines(report) + _unmapped_behaviour_lines(report)
        ).rstrip()

    # ------------------------------------------------------------------
    # 9. Indicators of compromise
    # ------------------------------------------------------------------

    def _section_indicators(self, report: MalwareReport, ctx: _Context) -> str:
        lines = [_heading(9, "Indicators of compromise", PER_ROW), ""]
        host = [row for row in ctx.iocs if row.kind not in _NETWORK_KINDS]
        network = [row for row in ctx.iocs if row.kind in _NETWORK_KINDS]
        if host:
            lines.extend([_subheading("9.1", "File and host indicators", PER_ROW), ""])
            lines.append(_row("Type", "Value", "Context", "Source", "Published"))
            lines.append(_divider(5))
            for row in host:
                lines.append(
                    _row(
                        row.type,
                        f"`{row.value}`",
                        row.context or "-",
                        row.source or "-",
                        row.published or "-",
                    )
                )
            if any(not row.published for row in host):
                lines.extend(
                    [
                        "",
                        "_A dash under Published: the platform's export mints no indicator "
                        "from this row. The judge's own bundle may still carry the value._",
                    ]
                )
            lines.append("")
        if network:
            reputation = ctx.reputations
            lines.extend([_subheading("9.2", "Network indicators", PER_ROW), ""])
            head = ["Type", "Value (defanged)", "Port/Path", "Context", "Source", "Published"]
            if reputation:
                head.append("Reputation (post-hoc enrichment)")
            lines.append(_row(*head))
            lines.append(_divider(len(head)))
            for row in network:
                cells = [
                    row.type,
                    f"`{defang(row.value, row.kind or '')}`",
                    _port_or_path(row, report),
                    row.context or "-",
                    row.source or "-",
                    row.published or "-",
                ]
                if reputation:
                    cells.append(reputation.get(row.value.strip().lower().rstrip("."), "-"))
                lines.append(_row(*cells))
            lines.append("")
        rid = str((report.run_summary or {}).get("report_id") or "{report_id}")
        lines.append(
            "Network values are defanged for reading. The STIX 2.1 bundle "
            f"(`/reports/{rid}/stix`) and the machine-readable list "
            f"(`/reports/{rid}/iocs`, see `docs/api.md`) carry them live."
        )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 10. Detection
    # ------------------------------------------------------------------

    def _section_detection(self, report: MalwareReport, ctx: _Context) -> str:
        blocks: list[str] = []
        rules = [s for s in report.sections if s.key in _RULE_SECTIONS]
        if rules:
            body = [_subheading("10.1", "Rules that matched this sample", MEASURED), ""]
            for section in rules:
                at = section.columns.index("Rule") if "Rule" in section.columns else 0
                names = [_one_line(row[at]) for row in section.rows if len(row) > at][:20]
                ids = f" ({', '.join(section.evidence_ids)})" if section.evidence_ids else ""
                body.append(
                    f"- {section.title}{ids}: " + (", ".join(f"`{n}`" for n in names) or "none")
                )
            body.extend(["", "_The rule sets and their licences are the tools' own; see §7.5._"])
            blocks.append("\n".join(body))
        if report.detection_signatures:
            body = [_subheading("10.2", "Draft detection rules", GENERATED), ""]
            body.append(
                "_Generated from templates over this report's own values and not reviewed "
                "by an analyst. Test before deploying._"
            )
            body.append("")
            for rule in report.detection_signatures:
                status = (
                    f"compile error: {rule.compile_error}" if rule.compile_error else "compiled"
                )
                source = (
                    f"; auto-generated from {', '.join(rule.source_evidence)}"
                    if rule.source_evidence
                    else ""
                )
                body.append(f"**{rule.kind.upper()}** `{rule.name}` — {status}{source}")
                body.append("")
                fence = rule.kind if rule.kind in {"yara", "sigma"} else ""
                body.extend([f"```{fence}", rule.body.rstrip(), "```", ""])
            blocks.append("\n".join(body).rstrip())
        hunting = [rec for rec in report.defensive_recommendations if rec.detection]
        if hunting:
            body = [_subheading("10.3", "Hunting notes", REPORT_MODEL), ""]
            body.extend(
                f"- {ctx.line(rec.detection)}"
                + (f" ({rec.technique_id})" if rec.technique_id else "")
                for rec in hunting
            )
            blocks.append("\n".join(body))
        if not blocks:
            return ""
        return "\n\n".join([_heading(10, "Detection", PER_SUBSECTION), *blocks])

    # ------------------------------------------------------------------
    # 11. Recommendations
    # ------------------------------------------------------------------

    def _section_recommendations(self, report: MalwareReport, ctx: _Context) -> str:
        recs = report.defensive_recommendations
        if not recs:
            return ""
        lines = [_heading(11, "Recommendations", REPORT_MODEL), ""]
        lines.append(_row("Priority", "Category", "Action", "Rationale", "Technique"))
        lines.append(_divider(5))
        order = {"P0": 0, "P1": 1, "P2": 2}
        for rec in sorted(recs, key=lambda r: order.get(r.priority, 9))[:8]:
            lines.append(
                _row(
                    rec.priority,
                    rec.category,
                    ctx.cell(rec.action),
                    ctx.cell(rec.rationale),
                    rec.technique_id or "-",
                )
            )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 12. Attribution and related activity
    # ------------------------------------------------------------------

    def _section_attribution(self, report: MalwareReport, ctx: _Context) -> str:
        attr = report.attribution
        blocks = [_heading(12, "Attribution and related activity", PER_SUBSECTION)]
        family = [_subheading("12.1", "Family", JUDGE), ""]
        family.append("**Family:** " + _family_words(report))
        if report.malware_category and str(report.malware_category).lower() != "unknown":
            family.append("")
            family.append(
                f"**Category:** {_one_line(report.malware_category)} "
                "_(a behavioural class, not a family)_"
            )
        blocks.append("\n".join(family))

        similarity: list[str] = []
        if attr.function_hash_matches:
            similarity.extend(
                [
                    "Function-hash matches (exact normalised-opcode hashes shared with "
                    "prior samples):",
                    "",
                    _row("Family", "Confidence", "Shared functions", "Example functions"),
                    _divider(4),
                ]
            )
            for match in attr.function_hash_matches[:10]:
                examples = (
                    ", ".join(f"`{f}`" for f in (match.get("example_functions") or [])[:3]) or "-"
                )
                similarity.append(
                    _row(
                        match.get("family") or "?",
                        f"{float(match.get('confidence') or 0.0):.2f}",
                        match.get("shared_functions") or "-",
                        examples,
                    )
                )
            similarity.append("")
        if attr.family_rag_candidates:
            similarity.extend(
                [
                    "Static-feature similarity to a reference fingerprint catalogue:",
                    "",
                    _row("Family", "Similarity", "Category", "Samples in catalogue"),
                    _divider(4),
                ]
            )
            for cand in attr.family_rag_candidates[:10]:
                similarity.append(
                    _row(
                        cand.get("family") or "?",
                        f"{float(cand.get('similarity') or 0.0):.3f}",
                        cand.get("malware_category") or "-",
                        cand.get("sample_count") or "-",
                    )
                )
            similarity.append("")
        if attr.similar_samples:
            similarity.extend(
                [
                    "Nearest previously analysed samples (behavioural distance):",
                    "",
                    _row("SHA-256", "Distance", "Source"),
                    _divider(3),
                ]
            )
            for sample in attr.similar_samples[:10]:
                dist = sample.get("distance")
                dist_str = f"{dist:.3f}" if isinstance(dist, int | float) else "-"
                similarity.append(
                    _row(f"`{sample.get('sha256', '?')}`", dist_str, sample.get("source") or "-")
                )
        if similarity:
            blocks.append(
                "\n".join([_subheading("12.2", "Similarity", MEASURED), "", *similarity]).rstrip()
            )

        if report.intro_background.strip():
            background = [_subheading("12.3", "Background", REPORT_MODEL), ""]
            text = report.intro_background.strip()
            background.append(ctx.prose(text))
            if not _EV_RE.search(text):
                background.extend(["", _UNCITED_NOTE])
            blocks.append("\n".join(background))
        return "\n\n".join(blocks)

    # ------------------------------------------------------------------
    # 13. Limitations and analysis notes
    # ------------------------------------------------------------------

    def _section_limitations(self, report: MalwareReport, ctx: _Context) -> str:
        summary = report.run_summary or {}
        lines = [_heading(13, "Limitations and analysis notes", MEASURED), ""]

        ran = [row for row in (summary.get("stages") or []) if isinstance(row, dict)]
        if ran:
            lines.extend(["**What ran:**", ""])
            for row in ran:
                state = "ran" if row.get("ran") else "did not run"
                why = f": {row['reason']}" if row.get("reason") and not row.get("ran") else ""
                lines.append(f"- `{row.get('key', '?')}` {state}{why}")
            lines.append("")
        lines.append(
            "Sandbox: "
            + (
                "a sandbox ran in this run." + ctx.partial_sentence()
                if ctx.sandbox_ran
                else "no sandbox tool was called in this run."
                if ctx.sandbox_known
                else "this report does not record whether a sandbox ran."
            )
        )
        lines.append("")

        evidence = summary.get("evidence") or {}
        if evidence:
            lines.append(
                f"**Evidence bounds:** {evidence.get('entries', 0)} ledger entries, "
                f"{evidence.get('ok', 0)} ok, {evidence.get('failed', 0)} failed, "
                f"{evidence.get('trimmed', 0)} trimmed to the budget."
            )
            lines.append("")
        failures = [row for row in (evidence.get("failures") or []) if isinstance(row, dict)]
        if failures:
            lines.extend(["**Tool failures:**", ""])
            for row in failures:
                tool = str(row.get("tool") or "tool")
                server = f" ({row['server']})" if row.get("server") else ""
                count = int(row.get("count") or 1)
                times = f" ×{count}" if count > 1 else ""
                message = str(row.get("error") or "").strip() or "failed"
                remedy = str(row.get("remediation") or "").strip()
                lines.append(
                    f"- `{tool}`{server}{times}: {message}" + (f" — {remedy}" if remedy else "")
                )
            lines.append("")
        truncation = summary.get("truncation")
        if isinstance(truncation, dict):
            trunc = SimpleNamespace(**truncation)
            partial = str(truncation.get("evidence_corpus_partial_reason") or "").strip()
            said = [
                f"Grounding searched less than this run produced ({partial})." if partial else "",
                corpus_held_sentence(trunc),
                bundle_loss_sentence(trunc),
            ]
            said = [s for s in said if s]
            if said:
                lines.extend([" ".join(said), ""])

        validation = summary.get("validation") or {}
        unresolved = [row for row in (validation.get("unresolved") or []) if isinstance(row, dict)]
        exports = [row for row in unresolved if str(row.get("code", "")).startswith("stix.")]
        others = [row for row in unresolved if row not in exports]
        if validation:
            not_run = validation.get("not_run") or []
            lines.append(
                f"**Validation:** {validation.get('retries', 0)} feedback retries, "
                f"{len(others)} finding(s) left unresolved"
                + (f"; checks that could not run: {', '.join(not_run)}" if not_run else "")
                + "."
            )
            lines.append("")
            for row in others:
                message = " ".join(str(row.get("message") or "").split())
                advisory = " (advisory)" if row.get("advisory") else ""
                lines.append(
                    f"- `{row.get('code', '')}` ({row.get('agent', '')}){advisory}: {message}"
                )
            if others:
                lines.append("")
        if exports:
            lines.extend(["**Export decisions:**", ""])
            for row in exports:
                message = " ".join(str(row.get("message") or "").split())
                lines.append(f"- `{row.get('code', '')}`: {message}")
            lines.append("")
        lost = [r for r in report.degradation_reasons if r.startswith("report section")]
        if lost:
            lines.extend(["**Report sections lost or trimmed:**", ""])
            lines.extend(f"- {reason}" for reason in lost)
            lines.append("")
        lines.append(
            "Values in Measured sections come from tools and are reported as the tools "
            "returned them. Assessed sections are the models' conclusions, reported as "
            "they wrote them; the checks above are the platform's comments on them."
        )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Appendices
    # ------------------------------------------------------------------

    def _appendix_evidence(self, report: MalwareReport, ctx: _Context) -> str:
        """The calls behind the report, then everything the tools and agents produced.

        Generic on purpose: a section knows whether it is a table, a key/value
        block, a list or a paragraph, and this renders that, so a tool server
        added tomorrow prints without a renderer change.
        """
        if not report.evidence_index and not report.sections:
            return ""
        lines = ["## Appendix A. Evidence index · _Measured_", ""]
        if report.evidence_index:
            lines.append(_row("ID", "Agent", "Server", "Tool", "OK", "Duration", "Trimmed"))
            lines.append(_divider(7))
            for row in report.evidence_index:
                lines.append(
                    _row(
                        row.id,
                        row.agent or "-",
                        row.server or "-",
                        row.tool or "-",
                        "yes" if row.ok else "no",
                        f"{row.duration_ms} ms",
                        "yes" if row.truncated else "no",
                    )
                )
            lines.append("")
        for section in report.sections:
            lines.extend([f"### {section.title}", ""])
            lines.extend(_evidence_body(section, ctx.prose))
            if section.evidence_ids:
                lines.extend(["", f"_Evidence: {', '.join(section.evidence_ids)}_"])
            lines.append("")
        return "\n".join(lines).rstrip()

    def _appendix_run(self, report: MalwareReport) -> str:
        run_summary = report.run_summary or {}
        if not run_summary:
            return ""
        lines = ["## Appendix B. Run summary · _Measured_", ""]
        elapsed = run_summary.get("elapsed_seconds")
        if elapsed is not None:
            lines.append(f"- Elapsed: {float(elapsed):.1f}s (the whole run, to this report)")
        for line in stage_duration_lines(run_summary.get("stages")):
            lines.append(f"- {line.replace('**', '').rstrip()}")
        verdict = run_summary.get("final_decision")
        if verdict:
            lines.append(f"- Verdict: {verdict}")
        negotiation = run_summary.get("negotiation") or {}
        if negotiation:
            rounds = negotiation.get("rounds_completed")
            reason = negotiation.get("termination_reason")
            final_conf = negotiation.get("final_confidence")
            if rounds is not None:
                lines.append(f"- Negotiation rounds: {rounds}")
            if reason:
                lines.append(f"- Termination reason: `{reason}`")
            if final_conf is not None:
                try:
                    lines.append(f"- Final confidence: {float(final_conf):.3f}")
                except (TypeError, ValueError):
                    pass
        ungrounded = run_summary.get("sections_without_evidence")
        if ungrounded:
            lines.append(f"- Report sections with no evidence: {ungrounded}")
        corroboration = run_summary.get("corroboration") or {}
        if corroboration:
            from maljan.analysis.corroboration import (
                corroboration_sources,
                published_count,
                technique_label,
            )

            multi = sum(1 for row in corroboration.values() if len(corroboration_sources(row)) > 1)
            asserted = sum(
                1
                for row in corroboration.values()
                if isinstance(row, dict) and row.get("asserted_by")
            )
            lines.append(
                f"- TTPs: {len(corroboration)} claimed, {published_count(corroboration)} "
                f"published, {multi} claimed by more than one source, "
                f"{asserted} asserted by a deterministic source"
            )
            lines.extend(
                [
                    "",
                    "**Corroboration per technique:**",
                    "",
                    "_Catalogue is the API table's association, shown for reference; "
                    "it is not a rule match and counts for nothing._",
                    "",
                    _row("Technique", "Asserted by", "Claimed by", "Catalogue"),
                    _divider(4),
                ]
            )
            for tid, row in sorted(corroboration.items()):
                if isinstance(row, dict):
                    asserted_by = ", ".join(row.get("asserted_by") or []) or "—"
                    claimed_by = ", ".join(row.get("claimed_by") or []) or "—"
                    associated = ", ".join(row.get("associated_by") or []) or "—"
                else:
                    asserted_by, claimed_by = "—", ", ".join(str(s) for s in row) or "—"
                    associated = "—"
                label = technique_label(str(tid), row if isinstance(row, dict) else None)
                lines.append(_row(label, asserted_by, claimed_by, associated))
        return "\n".join(lines)

    def _appendix_references(self, report: MalwareReport) -> str:
        lines = ["## Appendix C. References · _Reference_", ""]
        if not report.references:
            lines.append("_No external references._")
            return "\n".join(lines)
        for ref in report.references:
            note = f" — {ref.note}" if ref.note else ""
            lines.append(f"- [{ref.source}]({ref.url}){note}")
        return "\n".join(lines)

    def _appendix_method(self, report: MalwareReport, ctx: _Context) -> str:
        summary = report.run_summary or {}
        lines = ["## Appendix D. Methodology · _Reference_", ""]
        lines.append(
            "This report was produced by an automated team of language-model analysts "
            "working over tool servers. The analysts' claims were negotiated, a judge "
            "stated the verdict and the STIX bundle, and a report model wrote the "
            "assessed prose. Every tool call is in Appendix A."
        )
        lines.append("")
        profile = summary.get("profile") or {}
        analysts = ", ".join(profile.get("analysts") or []) or "the default team"
        lines.append(f"- Team: {profile.get('name') or 'default'} ({analysts})")
        stages = [
            str(row.get("key"))
            for row in (summary.get("stages") or [])
            if isinstance(row, dict) and row.get("ran")
        ]
        if stages:
            lines.append(f"- Stages run: {', '.join(stages)}")
        model = _model_line(summary.get("settings_snapshot"))
        if model:
            lines.append(f"- Models: {model}")
        servers = sorted({row.server for row in report.evidence_index if row.server})
        if servers:
            lines.append(f"- Tool servers called: {', '.join(servers)}")
        sandbox = (
            "called" if ctx.sandbox_ran else "not called" if ctx.sandbox_known else "not recorded"
        )
        lines.append(f"- Sandbox: {sandbox}")
        lines.append(f"- Report generated: {report.generated_at.isoformat()}")
        if report.version_history:
            lines.extend(["", _row("Version", "Date", "Authors", "Description"), _divider(4)])
            for row in report.version_history:
                lines.append(_row(row.version, row.date, row.authors, row.description))
        if report.disclaimer:
            lines.extend(["", f"_{report.disclaimer}_"])
        if report.acknowledgements:
            lines.extend(["", report.acknowledgements])
        for extra in report.appendices:
            lines.extend(["", extra])
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# What the sections share
# ---------------------------------------------------------------------------

# The evidence sections that are rule hits.
_RULE_SECTIONS = ("yara_matches", "capa_capabilities", "sigma_matches")

# How the report builder begins the reason for an absent summary. Spelled here
# rather than imported so the renderer keeps no import of the builder.
_NO_SUMMARY_PREFIX = "the report model wrote no summary"


def _inconclusive_reasons() -> tuple[str, ...]:
    from maljan.pipeline.outcome import INCONCLUSIVE_REASONS

    return tuple(INCONCLUSIVE_REASONS)


_INCONCLUSIVE = _inconclusive_reasons()


class _Context:
    """What several sections read, computed once per render."""

    def __init__(self, report: MalwareReport) -> None:
        self.report = report
        summary = report.run_summary or {}
        validation = summary.get("validation") or {}
        self.unresolved = [
            row for row in (validation.get("unresolved") or []) if isinstance(row, dict)
        ]
        self.verdict_findings = [
            {
                "code": str(row.get("code", "")),
                "message": " ".join(str(row.get("message") or "").split()),
            }
            for row in self.unresolved
            if str(row.get("code", "")).startswith("verdict.")
            or row.get("code") == "stix.indicator_type_contradicts_verdict"
        ]
        # The steps and items a survived finding names, read back from its
        # sentence: ``step <order> is marked observed``, ``configuration item <n>``.
        self.flow_findings = _named_in(
            self.unresolved, "report.flow_voice", r"step (\S+) is marked"
        )
        self.config_findings = {
            int(n)
            for n in _named_in(
                self.unresolved, "report.configuration_uncited", r"configuration item (\d+)"
            )
        }
        net = report.network
        self.sandbox_ran = (
            any(str(row.tool or "").startswith(_SANDBOX_TOOLS) for row in report.evidence_index)
            or report.dynamic is not None
            or any(
                getattr(row, "source", None) == "sandbox"
                for row in [*(net.domains if net else []), *(net.ips if net else [])]
                + list(net.urls if net else [])
            )
        )
        # Whether the report can say a sandbox did *not* run. A report stored
        # without its evidence index cannot, and says it does not know.
        self.sandbox_known = self.sandbox_ran or bool(report.evidence_index)
        self.iocs = _indicator_rows(report)
        indicators = [
            (row.value, row.kind or "") for row in self.iocs if row.kind in _NETWORK_KINDS
        ]
        net = report.network
        if net is not None:
            indicators += [(d.fqdn, "domain") for d in net.domains]
            indicators += [(ip.address, "ip") for ip in net.ips]
            indicators += [(u.url, "url") for u in net.urls]
        self.indicators = indicators
        self._defang = ProseDefanger(indicators)
        self.reputations = _reputations(report)

    @classmethod
    def of(cls, report: MalwareReport) -> _Context:
        return cls(report)

    def prose(self, text: str) -> str:
        """Model prose, with the run's own network indicators defanged in it."""
        return self._defang(text)

    def line(self, text: Any) -> str:
        """Model prose that has to stay on one line: a list item, a step."""
        return _one_line(self.prose(str(text or "")))

    def cell(self, text: Any) -> str:
        """A model-written table cell: defanged like prose, cut like every cell."""
        return _truncate(self.prose(str(text or "")), _CELL_LIMIT)

    def partial_sentence(self) -> str:
        """What made the evidence partial, as a sentence, or ``""``."""
        evidence = (self.report.run_summary or {}).get("evidence") or {}
        failed = int(evidence.get("failed") or 0)
        trimmed = int(evidence.get("trimmed") or 0)
        entries = int(evidence.get("entries") or 0)
        parts = []
        if failed:
            parts.append(f"{failed} of {entries} tool calls failed")
        if trimmed:
            parts.append(f"{trimmed} of {entries} ledger entries were trimmed")
        return f" The evidence is partial: {' and '.join(parts)}." if parts else ""


def _named_in(rows: list[dict[str, Any]], code: str, pattern: str) -> set[str]:
    """What the unresolved rows of one code name, read out of their sentences."""
    found: set[str] = set()
    for row in rows:
        if row.get("code") != code:
            continue
        match = re.search(pattern, str(row.get("message") or ""))
        if match:
            found.add(match.group(1))
    return found


def _indicator_rows(report: MalwareReport) -> list[ConsolidatedIOC]:
    """The IOC table's rows, answered by the publish rule on this render.

    Built on request from the stored report, the way ``/reports/{id}/iocs``
    is, so an enrichment that ran after the report was stored is reflected and
    a report stored before the table carried a kind prints in the new shape.
    """
    from maljan.reporting.builder import build_consolidated_iocs

    try:
        return build_consolidated_iocs(report)
    except Exception:  # noqa: BLE001 — the stored rows are the fallback
        logger.exception("markdown_renderer: the IOC table could not be rebuilt.")
        return [row for row in report.consolidated_iocs if row.kind]


def _reputations(report: MalwareReport) -> dict[str, str]:
    """A short reputation cell per network value the enrichment answered for."""
    out: dict[str, str] = {}
    net = report.network
    if net is None:
        return out
    rows = [(d.fqdn, d.reputation) for d in net.domains] + [
        (ip.address, ip.reputation) for ip in net.ips
    ]
    for value, rep in rows:
        if not isinstance(rep, dict) or "malicious" not in rep:
            continue
        try:
            total = sum(
                int(rep.get(k) or 0) for k in ("malicious", "suspicious", "harmless", "undetected")
            )
            name = rep.get("source") or "reputation"
            said = f"{name} {int(rep.get('malicious') or 0)}/{total} malicious"
        except (TypeError, ValueError):
            continue
        stamp = rep.get("last_analysis_date_unix")
        if isinstance(stamp, int) and stamp > 0:
            from datetime import UTC, datetime

            said += f" (analysed {datetime.fromtimestamp(stamp, tz=UTC).date().isoformat()})"
        out[value.strip().lower().rstrip(".")] = said
    return out


def _heading(number: int, title: str, voice: str) -> str:
    """An H2 with its section number and its voice tag."""
    return f"## {number}. {title} · _{voice}_"


def _subheading(number: str, title: str, voice: str) -> str:
    """An H3 with its subsection number and its voice tag."""
    label = f"{number} {title}" if number else title
    return f"### {label} · _{voice}_"


def _cite(ids: Iterable[str]) -> str:
    listed = [str(i) for i in ids if str(i).strip()]
    return f"[{', '.join(listed)}]" if listed else _NO_CITATION


def _ids_in(texts: Iterable[str]) -> list[str]:
    return list(dict.fromkeys(match for text in texts for match in _EV_RE.findall(str(text))))


def _subsection(
    number: str,
    title: str,
    prose: list[TechnicalSubsection | None],
    measured: list[str],
    ctx: _Context,
) -> str:
    """One capability subsection: the model's prose, then the tables that prove it.

    Omitted when it has neither. The prose is the report model's and is printed
    as written, defanged, with its citations after it; a subsection whose prose
    cites nothing says so once.
    """
    parts = [sub for sub in prose if sub is not None and sub.body.strip()]
    if not parts and not measured:
        return ""
    lines = [_subheading(number, title, REPORT_MODEL if parts else _voice_of(measured)), ""]
    for sub in parts:
        body = sub.body.strip()
        lines.append(ctx.prose(body))
        lines.append("")
        lines.append(_cite(sub.evidence_refs))
        if not sub.evidence_refs and not _EV_RE.search(body):
            lines.extend(["", _UNCITED_NOTE])
        lines.append("")
    lines.extend(measured)
    return "\n".join(lines).rstrip()


def _voice_of(measured: list[str]) -> str:
    """The voice of a subsection that holds tables only: the first one's label."""
    for line in measured:
        for voice in (OBSERVED, MEASURED, REPORT_MODEL, PER_ROW):
            if line.startswith(f"_{voice}:_"):
                return voice
    return MEASURED


def _ransomware_block(ta: Any, ctx: _Context) -> str:
    lines: list[str] = []
    spk = ta.service_process_kill
    if spk is not None and (spk.kill_list or spk.white_list or spk.mechanism):
        lines.extend(["Services and processes terminated:", ""])
        if spk.mechanism:
            lines.append(f"- Mechanism: {ctx.line(spk.mechanism)}")
        if spk.kill_list:
            lines.append(
                "- Kill list: " + ", ".join(f"`{_one_line(x)}`" for x in spk.kill_list[:30])
            )
        if spk.white_list:
            # The exclusions are often the more identifying half: a list that
            # spares the attacker's own tooling names it.
            lines.append("- Spared: " + ", ".join(f"`{_one_line(x)}`" for x in spk.white_list[:30]))
        lines.append("")
    if ta.shadow_copy_destruction:
        lines.extend(["Shadow copy destruction:", ""])
        lines.extend(f"- `{_one_line(cmd)}`" for cmd in ta.shadow_copy_destruction[:10])
        lines.append("")
    enc = ta.encryption_scheme
    if enc is not None:
        rows = [
            ("Cipher", enc.cipher),
            ("Mode", enc.mode),
            ("Library", enc.library),
            ("Key source", enc.key_source),
            ("Key management", enc.key_management),
            ("IV", enc.iv),
            ("File marker", enc.file_marker),
            ("Extension", enc.extension),
            ("Partial-encryption threshold", enc.partial_threshold),
            (
                "Per-file key",
                None if enc.per_file_key is None else ("yes" if enc.per_file_key else "no"),
            ),
            ("Evidence", enc.evidence_ref),
        ]
        present = [(label, value) for label, value in rows if value]
        if present:
            lines.extend(["Encryption scheme:", "", _row("Property", "Value"), _divider(2)])
            lines.extend(_row(label, ctx.cell(value)) for label, value in present)
            lines.append("")
    note = ta.ransom_note
    if note is not None and (note.filename or note.verbatim_content or note.sections):
        lines.extend(["Ransom note:", ""])
        if note.filename:
            lines.extend([f"Filename: `{_one_line(note.filename)}`", ""])
        if note.company_id_hash:
            lines.extend([f"Victim/company ID: `{_one_line(note.company_id_hash)}`", ""])
        if note.verbatim_content:
            # Fenced, not inlined: note text routinely contains markdown
            # characters and onion URLs, and the verbatim wording is what
            # links one incident to another.
            lines.extend(["```text", note.verbatim_content.strip()[:4000], "```", ""])
        elif note.sections:
            lines.extend(f"- {ctx.line(part)}" for part in note.sections[:10])
            lines.append("")
    if not lines:
        return ""
    return "\n".join(
        [_subheading("5.9", "Ransomware behaviour", REPORT_MODEL), "", *lines]
    ).rstrip()


def report_title(report: MalwareReport) -> str:
    """``<Family> <category> analysis`` when a family was named, else by format and hash."""
    attr = report.attribution
    family = _one_line(attr.family).strip()
    if family and family.lower() != "unknown" and attr.family_source != "sandbox":
        category = _one_line(report.malware_category).strip()
        if category and category.lower() != "unknown":
            return f"{family} {category} analysis"
        return f"{family} analysis"
    sha = (report.identity.hashes.sha256 or "unknown")[:12]
    fmt = _one_line(report.identity.file_type).strip()
    return f"{fmt} sample {sha} analysis" if fmt and fmt != "unknown" else f"Sample {sha} analysis"


def _verdict_words(report: MalwareReport) -> str:
    return f"{report.verdict} ({confidence_phrase(report.overall_confidence, 'the judge')})"


def _family_words(report: MalwareReport) -> str:
    attr = report.attribution
    family = _one_line(attr.family)
    if not family or family.lower() == "unknown":
        return "none attributed"
    if attr.family_source == "sandbox":
        return f"{family} (named by the sandbox's own classification; the judge named none)"
    said = f"{family} ({confidence_phrase(attr.family_confidence)})"
    if attr.family_evidence_ids:
        said += f" [{', '.join(attr.family_evidence_ids)}]"
    elif not attr.family_grounded:
        said += " (no evidence cited)"
    return said


def _verdict_line(report: MalwareReport) -> str:
    severity = report.severity.rating if report.severity else "not assessed"
    return (
        f"**Verdict:** {_verdict_words(report)} · **Severity:** {severity} · "
        f"**Family:** {_family_words(report)}"
    )


def _reputation_line(report: MalwareReport) -> str:
    """The sample's own reputation lookup, as the tool answered it, or that there was none."""
    entries = [row for row in report.evidence_index if row.tool in _REPUTATION_TOOLS]
    if not entries:
        return "no reputation lookup in this run"
    ids = {row.id for row in entries}
    facts: list[str] = []
    for section in report.sections:
        if not ids.intersection(section.evidence_ids) or section.kind != "kv":
            continue
        for row in section.rows:
            if len(row) >= 2 and str(row[0]).strip().lower() in _REPUTATION_KEYS:
                facts.append(f"{row[0]} {row[1]}")
    where = ", ".join(f"{row.tool} ({row.id})" for row in entries)
    return f"{where}: {'; '.join(facts[:6])}" if facts else f"{where}; see Appendix A"


def _environment_line(report: MalwareReport) -> str:
    """What the sandbox ran the sample in, as the sandbox's own report recorded it."""
    keys = ("machine", "platform", "os", "duration", "package", "options", "route", "timeout")
    facts: list[str] = []
    for section in report.sections:
        if not section.key.startswith("sandbox_") or section.kind != "kv":
            continue
        for row in section.rows:
            if len(row) >= 2 and str(row[0]).strip().lower() in keys:
                facts.append(f"{row[0]} {row[1]}")
    if facts:
        return "Environment: " + "; ".join(facts[:8]) + "."
    return "Environment: the sandbox's own report recorded no environment details in this run."


def _model_line(snapshot: Any) -> str:
    """The provider and model the run used, from its settings snapshot."""
    if not isinstance(snapshot, dict):
        return ""
    llm = snapshot.get("llm")
    if not isinstance(llm, dict):
        return ""
    provider = str(llm.get("provider") or "").strip()
    block = llm.get(provider) if provider else None
    model = str(block.get("model") or "").strip() if isinstance(block, dict) else ""
    return f"{provider} {model}".strip()


def _is_address(text: str) -> bool:
    try:
        ipaddress.ip_address(text.strip("[]"))
    except ValueError:
        return False
    return True


def _names_any(text: str, words: tuple[str, ...]) -> bool:
    lowered = text.lower()
    return any(word in lowered for word in words)


def _endpoint(value: str) -> str:
    """One model-written endpoint, defanged, and marked when no host outside could answer."""
    from maljan.extractors.network_extractor import host_is_public, url_host

    text = str(value or "").strip()
    if not text:
        return ""
    if "://" in text:
        kind, host = "url", url_host(text)
    elif _is_address(text):
        kind, host = "ip", text
    else:
        kind, host = "domain", text.split("/", 1)[0].split(":", 1)[0]
    written = f"`{defang(_truncate(text, _CELL_LIMIT), kind)}`"
    return (
        written if host_is_public(host) else f"{written} (not a host outside the analysed network)"
    )


def _port_or_path(row: ConsolidatedIOC, report: MalwareReport) -> str:
    if row.kind == "url":
        try:
            parsed = urlparse(row.value)
            port = f":{parsed.port}" if parsed.port else ""
            return (port + (parsed.path or "")) or "-"
        except ValueError:
            return "-"
    if row.kind == "ip" and report.network is not None:
        ports = [str(ip.port) for ip in report.network.ips if ip.address == row.value and ip.port]
        return ", ".join(ports) or "-"
    return "-"


def _tactic_key(cell: CapabilityCell) -> tuple[int, str]:
    order = _TACTIC_ORDER.index(cell.tactic) if cell.tactic in _TACTIC_ORDER else len(_TACTIC_ORDER)
    return order, cell.technique_id


def _attack_row(
    cell: CapabilityCell, mapping: Any, corroboration: dict[str, Any], ctx: _Context
) -> str:
    row = corroboration.get(cell.technique_id)
    asserted = list(row.get("asserted_by") or []) if isinstance(row, dict) else []
    claimed = list(row.get("claimed_by") or []) if isinstance(row, dict) else []
    source = ", ".join([*asserted, *claimed]) or ", ".join(cell.contributing_layers) or "-"
    confidence = "rule match" if asserted and not claimed else confidence_phrase(cell.confidence)
    if not cell.technique_id_valid:
        status = f"unverified id ({UNVERIFIED_TECHNIQUE_MARKER})"
    elif cell.not_published:
        status = f"claimed, not published: {_truncate(cell.not_published, 200)}"
    else:
        status = "published" + (
            ", corroborated" if mapping is not None and mapping.is_corroborated else ""
        )
    notes = [
        str(r.get("code"))
        for r in ctx.unresolved
        if str(r.get("code", "")).startswith("attck.")
        and cell.technique_id in str(r.get("message") or "")
    ]
    if notes:
        status += "; unresolved: " + ", ".join(dict.fromkeys(notes))
    tactic = f"{cell.tactic_name} ({cell.tactic})" if cell.tactic else cell.tactic_name
    procedure = ctx.cell(_truncate(cell.evidence[0], 160)) if cell.evidence else "-"
    return _row(
        tactic,
        cell.technique_id,
        cell.technique_name,
        procedure,
        source,
        confidence,
        status,
        ", ".join(_ids_in(cell.evidence)) or "-",
    )


def _import_rule_row(hit: dict[str, Any], mappings: dict[str, Any]) -> str:
    """One rule that fired over the import table, as a Measured row of the ATT&CK table.

    Every cell is escaped by ``_row``, and the import names most of all: they
    are the sample's own bytes, and a crafted import table carrying a pipe or a
    newline would otherwise reshape a table a human reads to make a call.
    """
    tid = str(hit.get("technique_id") or "?")
    apis = ", ".join(f"`{a}`" for a in (hit.get("matched_apis") or [])[:6]) or "-"
    rule = str(hit.get("rule") or "").strip()
    procedure = (f"rule {rule} over " if rule else "") + f"imports {apis}; fires on "
    procedure += str(hit.get("benign_rate") or "not measured")
    status = "published" if tid in mappings else "rule match, not published"
    return _row(
        "-",
        tid,
        hit.get("name") or "-",
        procedure,
        f"pipeline:{hit.get('source') or '-'}",
        "rule match",
        status,
        hit.get("evidence_id") or "-",
    )


def _spawned(roots: list[ProcessNode]) -> list[ProcessNode]:
    """Every process below the roots: the ones the sample started."""
    out: list[ProcessNode] = []
    for root in roots:
        for child in root.children:
            out.append(child)
            out.extend(_spawned([child]))
    return out


def _as_is(text: str) -> str:
    return text


def _evidence_body(section: Any, write: Callable[[str], str] = _as_is) -> list[str]:
    """One evidence section's rows, in whichever shape it carries.

    A section may carry both. Rows are what a tool found; the text beside them
    is what this system has to say about how it got them — that the answer was
    too big for the prompt and the table below is a page of it. It goes above
    the rows, as prose rather than as a fenced block, because a reader has to
    know a table is partial before they read it as complete. A section with
    nothing but text is a tool's own output and keeps its fence.
    """
    rows = _evidence_rows(section, write)
    if not rows:
        return ["```", write(section.text), "```"] if section.text else []
    return [write(section.text), ""] + rows if section.text else rows


def _evidence_rows(section: Any, write: Callable[[str], str] = _as_is) -> list[str]:
    """The tabular or bulleted half of a section, or nothing.

    ``write`` is how a cell's text is written: the report's own network
    indicators defanged in it, where a section is printed for reading.
    """
    if section.kind in {"table", "kv"} and section.rows:
        columns = section.columns or [f"Column {i + 1}" for i in range(len(section.rows[0]))]
        out = [_row(*columns), _divider(len(columns))]
        for row in section.rows:
            cells = [_truncate(write(str(cell)), 160) for cell in row]
            cells += [""] * (len(columns) - len(cells))
            out.append(_row(*cells[: len(columns)]))
        return out
    if section.kind == "list" and section.items:
        return [f"- {_one_line(_truncate(write(str(item)), 200))}" for item in section.items]
    return []


def _not_published_lines(report: MalwareReport) -> list[str]:
    """The techniques a producer claimed and this report does not publish.

    They are in the table above, with the reason in the Status column. This
    short list under it is for a reader who scans headings: the claims are in
    none of the technique surfaces — not the References, not the STIX
    attack-patterns, not ``/reports/{id}/mitre``.
    """
    rows = [
        cell for cell in (getattr(report, "capability_matrix", None) or []) if cell.not_published
    ]
    if not rows:
        return []
    lines = ["", "### Claims that were not published as techniques", ""]
    lines.extend(
        f"- {cell.technique_id} {cell.technique_name}: {_truncate(cell.not_published, 300)}"
        for cell in rows
    )
    return lines


def _unmapped_behaviour_lines(report: MalwareReport) -> list[str]:
    """The behaviours the verdict named and could not map to a technique.

    Printed under the table and never inside it: a behaviour with no technique
    id is not an ATT&CK technique.
    """
    names = list(getattr(report, "unmapped_behaviours", None) or [])
    if not names:
        return []
    lines = ["", "### Behaviours with no mapped technique", ""]
    lines.extend(f"- {_truncate(name, 200)}" for name in names)
    lines.append("")
    lines.append(
        "_Named in the verdict without a MITRE ATT&CK technique id after the id was "
        "asked for. They are not ATT&CK techniques and are not counted as any._"
    )
    return lines


def _row(*cells: Any) -> str:
    """One table row, assembled from its cells so the cells cannot assemble it.

    Escaping per call site was the first attempt and it does not hold: it is a
    rule nothing enforces, and the evidence is that a careful sweep with a test
    behind it still left the PE Sections table — whose first cell is eight raw
    bytes out of the section header — building its own row. A row a caller
    cannot write by hand cannot be written wrong, so every table in this
    renderer goes through here, header rows included, and
    ``test_a_table_row_is_never_assembled_by_hand`` fails the build if a new one
    does not.

    A cell arrives composed: backticks, a parenthetical, a format spec are the
    caller's business. What is not the caller's business is the separator, so
    the escaping happens here, once, on whatever the cell turned out to be.
    """
    return "| " + " | ".join(_cell(cell) for cell in cells) + " |"


def _divider(columns: int) -> str:
    """The rule under a table's header, for as many columns as it has."""
    return "|" + "---|" * columns


def _cell(value: Any) -> str:
    """One table cell's text, with what would break the table taken out of it.

    Every string in this report that a sample, a sandbox, a tool payload or a
    model wrote is free text, and a Markdown table is one of the few places
    where free text is structural: a single ``|`` adds a column and shifts
    every cell after it, and a newline ends the row and orphans every row
    below. The worst case is not theoretical — an import name is the sample's
    own bytes and a URL, a registry key and a dropped file's path all come
    from the sample too — and the table it would wreck is one a human reads to
    make a call. Cheaper to escape at the cell than to trust each producer.

    Not a security control. ``markdown-it`` runs with ``html=False`` and React
    escapes text, so nothing here is about injection; this is table integrity.
    """
    if value is None:
        return ""
    return str(value).replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def _one_line(value: Any) -> str:
    """A value that has to stay on its line: its line breaks become spaces."""
    return " ".join(str(value or "").splitlines())


def _truncate(value: Any, length: int) -> str:
    if value is None:
        return ""
    s = str(value)
    if len(s) <= length:
        return s
    return s[: length - 1] + "…"


def _process_tree_lines(node: ProcessNode, depth: int) -> list[str]:
    indent = "  " * depth
    prefix = "└─ " if depth > 0 else ""
    label = _one_line(node.name) or f"pid={node.pid}"
    extra = f"  ({_one_line(node.command_line)})" if node.command_line else ""
    line = f"{indent}{prefix}pid={node.pid} ppid={node.ppid} {label}{extra}"
    out = [line]
    if node.injected_into:
        out.append(f"{indent}    [injected_into={', '.join(str(p) for p in node.injected_into)}]")
    for child in node.children:
        out.extend(_process_tree_lines(child, depth + 1))
    return out


def _registry_row(reg: RegistryMod) -> str:
    return _row(
        reg.hive,
        f"`{_truncate(reg.key, _CELL_LIMIT)}`",
        f"`{_truncate(reg.value_name or '-', 80)}`",
        reg.operation,
    )


def _signature_row(sig: SandboxSignature) -> str:
    ttps = ", ".join(sig.technique_ids) if sig.technique_ids else "-"
    return _row(sig.name, sig.severity, ttps, _truncate(sig.description or "-", _CELL_LIMIT))
