"""The uv export is turned into a dependency-graph snapshot without touching the network."""

from __future__ import annotations

import importlib.util
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[3] / "scripts" / "ci" / "submit_dependency_snapshot.py"


def _module():
    spec = importlib.util.spec_from_file_location("submit_dependency_snapshot", SCRIPT)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


SAMPLE = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen
-e .
    # via maljan-api
-e ./apps/api
alembic==1.20.0
    # via
    #   maljan
Pillow==12.3.0 ; python_full_version >= '3.10'
uvicorn[standard]==0.46.0
python_multipart==0.0.32
"""


def test_requirements_are_parsed_and_names_normalised():
    mod = _module()
    assert mod.parse_requirements(SAMPLE) == {
        "alembic": "1.20.0",
        "pillow": "12.3.0",
        "uvicorn": "0.46.0",
        "python-multipart": "0.0.32",
    }


def test_snapshot_marks_dev_only_packages_and_carries_the_manifest():
    mod = _module()
    runtime = {"alembic": "1.20.0"}
    everything = {"alembic": "1.20.0", "pytest": "9.1.1"}
    snap = mod.build_snapshot(
        runtime, everything, sha="abc", ref="refs/heads/main", job_id="1", correlator="ci-uv"
    )
    resolved = snap["manifests"]["uv.lock"]["resolved"]
    assert snap["manifests"]["uv.lock"]["file"] == {"source_location": "uv.lock"}
    assert resolved["pkg:pypi/alembic@1.20.0"]["scope"] == "runtime"
    assert resolved["pkg:pypi/pytest@9.1.1"]["scope"] == "development"
    assert snap["sha"] == "abc" and snap["ref"] == "refs/heads/main"
    assert snap["job"] == {"correlator": "ci-uv", "id": "1"}
    assert snap["scanned"].endswith("Z")
