#!/usr/bin/env python3
"""Build the Windows API behaviour map and the API→ATT&CK map.

Offline, operator-run, never imported by the pipeline — the same contract as
``build_family_feature_kb.py`` and ``build_attck_case_kb.py``.

Why the curated lists live here rather than in the JSON: the JSON is the
artifact, this is the source. Keeping the vocabulary in reviewable Python means
a reader can see *why* ``NtUnmapViewOfSection`` is process-injection and
``RegOpenKeyExA`` is not suspicious, and a contributor can extend a list without
hand-editing a 600-entry JSON literal and getting the commas wrong.

**Provenance.** Every name below is a public Win32/NT API symbol and every
technique ID is from the public MITRE ATT&CK catalog. Nothing here is copied
from another tool's data files; the *architecture* (one resolved-import set
projected onto two taxonomies, behind a reverse index) is the idea worth
borrowing, the bytes are not.

Usage::

    uv run python scripts/build_api_capability_db.py
    make prepare-api-db
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parent.parent
_BEHAVIOUR_OUT = _ROOT / "data" / "api_behaviour_map_v1.json"
_ATTCK_OUT = _ROOT / "data" / "api_attck_map_v1.json"
_VALID_IDS = _ROOT / "data" / "attck_valid_ids.json"

# ---------------------------------------------------------------------------
# Tiers
# ---------------------------------------------------------------------------
# ``high``/``medium`` set ImportRow.is_suspicious; ``informational`` does not.
#
# The split is the whole point of this file. Categorising RegOpenKeyExA is
# useful — it tells the prompt and the ATT&CK mapper what the binary touches.
# Calling it *suspicious* is not: every Windows program opens registry keys, and
# a "suspicious imports" table that lists all of them tells a reader nothing.
#
# Rule of thumb applied below: a category is high/medium when its presence in an
# import table is itself unusual for ordinary software, and informational when
# the API is ubiquitous and only the *pattern* of use carries signal.

HIGH = "high"
MEDIUM = "medium"
INFO = "informational"


# ---------------------------------------------------------------------------
# Windows behaviour categories
# ---------------------------------------------------------------------------
# The eight existing category names are frozen and must not be renamed: they are
# consumed by capability_matrix.py, ghidra_tool_selector.py,
# import_capability_layer.py, and — invisibly — by the vendored
# data/family_fingerprints_v1.json, whose description text embeds this exact
# vocabulary. A rename desynchronises the family-RAG query from its catalog
# inside one embedding space, with no exception and no test failure.

WINDOWS_CATEGORIES: dict[str, tuple[str, list[str]]] = {
    # ---------------------------------------------------------------- frozen 8
    "process_injection": (
        HIGH,
        [
            "VirtualAlloc",
            "VirtualAllocEx",
            "VirtualProtect",
            "VirtualProtectEx",
            "WriteProcessMemory",
            "ReadProcessMemory",
            "CreateRemoteThread",
            "CreateRemoteThreadEx",
            "NtCreateThreadEx",
            "RtlCreateUserThread",
            "QueueUserAPC",
            "NtQueueApcThread",
            "SetWindowsHookEx",
            "SetWindowsHookExA",
            "SetWindowsHookExW",
            "NtUnmapViewOfSection",
            "ZwUnmapViewOfSection",
            "NtMapViewOfSection",
            "ZwMapViewOfSection",
            "NtWriteVirtualMemory",
            "ZwWriteVirtualMemory",
            "NtReadVirtualMemory",
            "NtAllocateVirtualMemory",
            "ZwAllocateVirtualMemory",
            "NtProtectVirtualMemory",
            "OpenProcess",
            "OpenThread",
            "SuspendThread",
            "ResumeThread",
            "SetThreadContext",
            "GetThreadContext",
            "Wow64SetThreadContext",
            "Wow64GetThreadContext",
            "CreateFileMapping",
            "CreateFileMappingA",
            "CreateFileMappingW",
            "MapViewOfFile",
            "MapViewOfFileEx",
            "UnmapViewOfFile",
            "NtCreateSection",
            "ZwCreateSection",
            "RtlMoveMemory",
            "SetPropA",
            "SetPropW",
            "EnumChildWindows",
        ],
    ),
    "anti_debug": (
        HIGH,
        [
            "IsDebuggerPresent",
            "CheckRemoteDebuggerPresent",
            "NtQueryInformationProcess",
            "ZwQueryInformationProcess",
            "NtSetInformationThread",
            "ZwSetInformationThread",
            "OutputDebugStringA",
            "OutputDebugStringW",
            "DebugActiveProcess",
            "DebugBreak",
            "NtQuerySystemInformation",
            "ZwQuerySystemInformation",
            "GetTickCount",
            "GetTickCount64",
            "QueryPerformanceCounter",
            "QueryPerformanceFrequency",
            "NtQueryPerformanceCounter",
            "GetSystemTimeAsFileTime",
            "timeGetTime",
            "RtlGetVersion",
            "NtClose",
            "GetThreadInformation",
            "SetHandleInformation",
            "NtYieldExecution",
            "SwitchToThread",
        ],
    ),
    "network": (
        MEDIUM,
        [
            "WSAStartup",
            "WSACleanup",
            "WSASocketA",
            "WSASocketW",
            "WSAConnect",
            "WSASend",
            "WSARecv",
            "WSAIoctl",
            "WSAGetLastError",
            "WSAAsyncSelect",
            "socket",
            "connect",
            "send",
            "sendto",
            "recv",
            "recvfrom",
            "bind",
            "listen",
            "accept",
            "closesocket",
            "shutdown",
            "select",
            "ioctlsocket",
            "gethostbyname",
            "gethostname",
            "getaddrinfo",
            "GetAddrInfoW",
            "freeaddrinfo",
            "inet_addr",
            "inet_ntoa",
            "inet_pton",
            "htons",
            "ntohs",
            "InternetOpenA",
            "InternetOpenW",
            "InternetOpenUrlA",
            "InternetOpenUrlW",
            "InternetConnectA",
            "InternetConnectW",
            "InternetReadFile",
            "InternetWriteFile",
            "InternetCloseHandle",
            "InternetSetOptionA",
            "InternetQueryOptionA",
            "InternetCrackUrlA",
            "InternetGetConnectedState",
            "HttpOpenRequestA",
            "HttpOpenRequestW",
            "HttpSendRequestA",
            "HttpSendRequestW",
            "HttpSendRequestExA",
            "HttpQueryInfoA",
            "HttpAddRequestHeadersA",
            "HttpEndRequestA",
            "URLDownloadToFileA",
            "URLDownloadToFileW",
            "URLDownloadToCacheFileA",
            "WinHttpOpen",
            "WinHttpConnect",
            "WinHttpOpenRequest",
            "WinHttpSendRequest",
            "WinHttpReceiveResponse",
            "WinHttpReadData",
            "WinHttpWriteData",
            "WinHttpQueryHeaders",
            "WinHttpSetOption",
            "WinHttpCloseHandle",
            "WinHttpCrackUrl",
            "WinHttpQueryDataAvailable",
            "WinHttpSetTimeouts",
            "DnsQuery_A",
            "DnsQuery_W",
            "DnsQueryEx",
            "DnsFree",
            "FtpPutFileA",
            "FtpGetFileA",
            "FtpOpenFileA",
            "IcmpSendEcho",
            "IcmpCreateFile",
            "NetShareEnum",
            "NetUseAdd",
            "NetServerEnum",
            "WNetAddConnection2A",
            "WNetOpenEnumA",
            "WNetEnumResourceA",
            "SendARP",
            "GetAdaptersInfo",
            "GetAdaptersAddresses",
            "GetNetworkParams",
            "GetIfTable",
            "GetTcpTable",
            "GetExtendedTcpTable",
            "GetUdpTable",
            "CoInternetSetFeatureEnabled",
            "ObtainUserAgentString",
        ],
    ),
    "crypto": (
        MEDIUM,
        [
            "CryptAcquireContextA",
            "CryptAcquireContextW",
            "CryptReleaseContext",
            "CryptCreateHash",
            "CryptHashData",
            "CryptGetHashParam",
            "CryptDestroyHash",
            "CryptDeriveKey",
            "CryptGenKey",
            "CryptImportKey",
            "CryptExportKey",
            "CryptDestroyKey",
            "CryptSetKeyParam",
            "CryptGetKeyParam",
            "CryptEncrypt",
            "CryptDecrypt",
            "CryptGenRandom",
            "CryptProtectData",
            "CryptUnprotectData",
            "CryptProtectMemory",
            "CryptUnprotectMemory",
            "CryptStringToBinaryA",
            "CryptBinaryToStringA",
            "BCryptOpenAlgorithmProvider",
            "BCryptCloseAlgorithmProvider",
            "BCryptGenerateSymmetricKey",
            "BCryptGenerateKeyPair",
            "BCryptImportKey",
            "BCryptImportKeyPair",
            "BCryptExportKey",
            "BCryptDestroyKey",
            "BCryptEncrypt",
            "BCryptDecrypt",
            "BCryptHashData",
            "BCryptCreateHash",
            "BCryptFinishHash",
            "BCryptGenRandom",
            "BCryptSetProperty",
            "BCryptDeriveKeyPBKDF2",
            "BCryptSignHash",
            "BCryptVerifySignature",
            "NCryptOpenStorageProvider",
            "NCryptOpenKey",
            "NCryptDecrypt",
            "NCryptEncrypt",
            "NCryptExportKey",
            "NCryptImportKey",
            "SystemFunction036",
            "RtlEncryptMemory",
            "RtlDecryptMemory",
            "CertOpenSystemStoreA",
            "CertOpenStore",
            "CertFindCertificateInStore",
            "CertEnumCertificatesInStore",
            "PFXImportCertStore",
        ],
    ),
    "filesystem": (
        INFO,
        [
            "CreateFileA",
            "CreateFileW",
            "CreateFile2",
            "ReadFile",
            "ReadFileEx",
            "WriteFile",
            "WriteFileEx",
            "CloseHandle",
            "SetFilePointer",
            "SetFilePointerEx",
            "GetFileSize",
            "GetFileSizeEx",
            "FlushFileBuffers",
            "DeleteFileA",
            "DeleteFileW",
            "MoveFileA",
            "MoveFileW",
            "MoveFileExA",
            "MoveFileExW",
            "CopyFileA",
            "CopyFileW",
            "CopyFileExA",
            "ReplaceFileA",
            "CreateDirectoryA",
            "CreateDirectoryW",
            "RemoveDirectoryA",
            "RemoveDirectoryW",
            "SetCurrentDirectoryA",
            "GetCurrentDirectoryA",
            "FindFirstFileA",
            "FindFirstFileW",
            "FindNextFileA",
            "FindNextFileW",
            "FindClose",
            "GetFileAttributesA",
            "GetFileAttributesW",
            "SetFileAttributesA",
            "SetFileAttributesW",
            "GetFileAttributesExA",
            "SetFileTime",
            "GetFileTime",
            "SetEndOfFile",
            "GetTempPathA",
            "GetTempPathW",
            "GetTempFileNameA",
            "GetTempFileNameW",
            "GetWindowsDirectoryA",
            "GetSystemDirectoryA",
            "GetSystemWow64DirectoryA",
            "SHGetFolderPathA",
            "SHGetFolderPathW",
            "SHGetSpecialFolderPathA",
            "SHGetKnownFolderPath",
            "PathAppendA",
            "PathCombineA",
            "PathFileExistsA",
            "GetModuleFileNameA",
            "GetModuleFileNameW",
            "GetFullPathNameA",
            "GetLongPathNameA",
            "GetShortPathNameA",
            "GetVolumeInformationA",
            "GetLogicalDrives",
            "GetLogicalDriveStringsA",
            "GetDriveTypeA",
            "GetDiskFreeSpaceExA",
            "CreateHardLinkA",
            "DeviceIoControl",
            "SetFileInformationByHandle",
            "NtCreateFile",
            "NtWriteFile",
            "NtReadFile",
            "NtDeleteFile",
            "NtSetInformationFile",
            "NtQueryInformationFile",
            "SHFileOperationA",
            "SHFileOperationW",
            "CreateIoCompletionPort",
        ],
    ),
    "registry": (
        INFO,
        [
            "RegOpenKeyA",
            "RegOpenKeyW",
            "RegOpenKeyExA",
            "RegOpenKeyExW",
            "RegCreateKeyA",
            "RegCreateKeyW",
            "RegCreateKeyExA",
            "RegCreateKeyExW",
            "RegCloseKey",
            "RegDeleteKeyA",
            "RegDeleteKeyW",
            "RegDeleteKeyExA",
            "RegDeleteValueA",
            "RegDeleteValueW",
            "RegDeleteTreeA",
            "RegSetValueA",
            "RegSetValueW",
            "RegSetValueExA",
            "RegSetValueExW",
            "RegQueryValueA",
            "RegQueryValueW",
            "RegQueryValueExA",
            "RegQueryValueExW",
            "RegQueryInfoKeyA",
            "RegQueryInfoKeyW",
            "RegEnumKeyA",
            "RegEnumKeyExA",
            "RegEnumKeyExW",
            "RegEnumValueA",
            "RegEnumValueW",
            "RegFlushKey",
            "RegSaveKeyA",
            "RegRestoreKeyA",
            "RegLoadKeyA",
            "RegUnLoadKeyA",
            "RegConnectRegistryA",
            "RegNotifyChangeKeyValue",
            "RegGetValueA",
            "RegOverridePredefKey",
            "SHGetValueA",
            "SHSetValueA",
            "SHDeleteKeyA",
            "NtOpenKey",
            "NtSetValueKey",
            "NtQueryValueKey",
            "NtDeleteKey",
            "NtEnumerateKey",
            "NtEnumerateValueKey",
            "ZwOpenKey",
            "ZwSetValueKey",
        ],
    ),
    "privilege": (
        HIGH,
        [
            "AdjustTokenPrivileges",
            "OpenProcessToken",
            "OpenThreadToken",
            "LookupPrivilegeValueA",
            "LookupPrivilegeValueW",
            "LookupPrivilegeNameA",
            "PrivilegeCheck",
            "ImpersonateLoggedOnUser",
            "ImpersonateNamedPipeClient",
            "ImpersonateSelf",
            "RevertToSelf",
            "SetThreadToken",
            "DuplicateToken",
            "DuplicateTokenEx",
            "CreateProcessAsUserA",
            "CreateProcessAsUserW",
            "CreateProcessWithTokenW",
            "CreateProcessWithLogonW",
            "LogonUserA",
            "LogonUserW",
            "SetTokenInformation",
            "GetTokenInformation",
            "CheckTokenMembership",
            "AllocateAndInitializeSid",
            "InitializeSecurityDescriptor",
            "SetSecurityDescriptorDacl",
            "SetSecurityInfo",
            "SetNamedSecurityInfoA",
            "GetSecurityInfo",
            "ConvertStringSecurityDescriptorToSecurityDescriptorA",
            "NtAdjustPrivilegesToken",
            "RtlAdjustPrivilege",
            "SeDebugPrivilege",
            "CoImpersonateClient",
            "OpenSCManagerA",
            "OpenSCManagerW",
        ],
    ),
    "execution": (
        MEDIUM,
        [
            "WinExec",
            "ShellExecuteA",
            "ShellExecuteW",
            "ShellExecuteExA",
            "ShellExecuteExW",
            "CreateProcessA",
            "CreateProcessW",
            "CreateProcessInternalW",
            "NtCreateUserProcess",
            "RtlCreateProcessParameters",
            "system",
            "_wsystem",
            "_popen",
            "_execv",
            "_spawnl",
            "LoadLibraryA",
            "LoadLibraryW",
            "LoadLibraryExA",
            "LoadLibraryExW",
            "GetProcAddress",
            "GetModuleHandleA",
            "GetModuleHandleW",
            "GetModuleHandleExA",
            "FreeLibrary",
            "LdrLoadDll",
            "LdrGetProcedureAddress",
            "LdrGetDllHandle",
            "DisableThreadLibraryCalls",
            "CreateThread",
            "ExitThread",
            "TerminateThread",
            "ExitProcess",
            "TerminateProcess",
            "NtTerminateProcess",
            "WaitForSingleObject",
            "WaitForMultipleObjects",
            "CreateJobObjectA",
            "AssignProcessToJobObject",
            "CoCreateInstance",
            "CoCreateInstanceEx",
            "CoInitialize",
            "CoInitializeEx",
            "CoGetObject",
            "CLSIDFromProgID",
            "OleRun",
            "IDispatch",
            "WScriptShell",
            "ScriptControl",
        ],
    ),
    # --------------------------------------------------------------- new four
    "discovery": (
        INFO,
        [
            "GetComputerNameA",
            "GetComputerNameW",
            "GetComputerNameExA",
            "GetUserNameA",
            "GetUserNameW",
            "GetUserNameExA",
            "GetSystemInfo",
            "GetNativeSystemInfo",
            "GetVersionExA",
            "GetVersionExW",
            "GetSystemMetrics",
            "GetSystemDefaultLangID",
            "GetUserDefaultLangID",
            "GetUserDefaultUILanguage",
            "GetSystemDefaultUILanguage",
            "GetLocaleInfoA",
            "GetLocaleInfoW",
            "GetTimeZoneInformation",
            "GetKeyboardLayout",
            "GetKeyboardLayoutList",
            "CreateToolhelp32Snapshot",
            "Process32First",
            "Process32FirstW",
            "Process32Next",
            "Process32NextW",
            "Module32First",
            "Module32Next",
            "Thread32First",
            "Thread32Next",
            "Heap32First",
            "Heap32ListFirst",
            "EnumProcesses",
            "EnumProcessModules",
            "EnumProcessModulesEx",
            "GetModuleBaseNameA",
            "GetProcessImageFileNameA",
            "QueryFullProcessImageNameA",
            "GetCurrentProcessId",
            "GetCurrentThreadId",
            "GetProcessId",
            "EnumWindows",
            "FindWindowA",
            "FindWindowW",
            "FindWindowExA",
            "GetWindowTextA",
            "GetWindowTextW",
            "GetForegroundWindow",
            "GetWindowThreadProcessId",
            "GetClassNameA",
            "IsWindowVisible",
            "EnumDesktopWindows",
            "EnumDesktopsA",
            "GetDesktopWindow",
            "GlobalMemoryStatusEx",
            "GetPhysicallyInstalledSystemMemory",
            "GetDiskFreeSpaceA",
            "EnumServicesStatusA",
            "EnumServicesStatusExA",
            "QueryServiceConfigA",
            "EnumDependentServicesA",
            "NetUserGetInfo",
            "NetUserEnum",
            "NetLocalGroupGetMembers",
            "NetWkstaGetInfo",
            "NetGetJoinInformation",
            "DsGetDcNameA",
            "LookupAccountSidA",
            "LookupAccountNameA",
            "GetCurrentHwProfileA",
            "EnumSystemLocalesA",
            "IsProcessorFeaturePresent",
            "GetProductInfo",
            "WTSEnumerateSessionsA",
            "WTSQuerySessionInformationA",
            "GetLastInputInfo",
            "GetCursorPos",
        ],
    ),
    "persistence": (
        HIGH,
        [
            "CreateServiceA",
            "CreateServiceW",
            "OpenServiceA",
            "OpenServiceW",
            "StartServiceA",
            "StartServiceW",
            "StartServiceCtrlDispatcherA",
            "ControlService",
            "DeleteService",
            "ChangeServiceConfigA",
            "ChangeServiceConfig2A",
            "RegisterServiceCtrlHandlerA",
            "SetServiceStatus",
            "QueryServiceStatusEx",
            "CloseServiceHandle",
            "NetScheduleJobAdd",
            "NetScheduleJobEnum",
            "ITaskScheduler",
            "ITaskService",
            "IRegisteredTask",
            "ITaskFolder",
            "CoTaskMemAlloc",
            "SHSetValueW",
            "CreateProcessAsUserW",
            "RegisterEventSourceA",
            "ReportEventA",
            "WriteProfileStringA",
            "GetPrivateProfileStringA",
            "CreateMutexA",
            "CreateMutexW",
            "CreateMutexExA",
            "OpenMutexA",
            "OpenMutexW",
            "CreateEventA",
            "CreateEventW",
            "OpenEventA",
            "CreateSemaphoreA",
            "ReleaseMutex",
            "SHGetSpecialFolderLocation",
            "SHChangeNotify",
            "IWbemLocator",
            "IWbemServices",
            "IWbemClassObject",
            "CoSetProxyBlanket",
            "CoInitializeSecurity",
        ],
    ),
    "keylogging": (
        HIGH,
        [
            "GetAsyncKeyState",
            "GetKeyState",
            "GetKeyboardState",
            "SetKeyboardState",
            "GetKeyNameTextA",
            "MapVirtualKeyA",
            "ToAscii",
            "ToUnicode",
            "ToUnicodeEx",
            "RegisterRawInputDevices",
            "GetRawInputData",
            "GetRawInputDeviceList",
            "AttachThreadInput",
            "BlockInput",
            "keybd_event",
            "mouse_event",
            "SendInput",
            "GetMessageA",
            "GetMessageW",
            "PeekMessageA",
            "TranslateMessage",
            "DispatchMessageA",
            "SetWinEventHook",
            "RegisterHotKey",
            "GetClipboardData",
            "SetClipboardData",
            "OpenClipboard",
            "CloseClipboard",
            "EmptyClipboard",
            "IsClipboardFormatAvailable",
            "AddClipboardFormatListener",
            "BitBlt",
            "StretchBlt",
            "CreateCompatibleBitmap",
            "CreateCompatibleDC",
            "GetDC",
            "GetWindowDC",
            "GetDIBits",
            "SelectObject",
            "PrintWindow",
            "waveInOpen",
            "waveInStart",
            "capCreateCaptureWindowA",
        ],
    ),
    "evasion": (
        HIGH,
        [
            "NtSetInformationProcess",
            "ZwSetInformationProcess",
            "RtlSetProcessIsCritical",
            "NtRaiseHardError",
            "SetProcessMitigationPolicy",
            "SetProcessValidCallTargets",
            "AddVectoredExceptionHandler",
            "RemoveVectoredExceptionHandler",
            "SetUnhandledExceptionFilter",
            "UnhandledExceptionFilter",
            "RtlAddVectoredExceptionHandler",
            "RaiseException",
            "IsWow64Process",
            "IsWow64Process2",
            "Wow64DisableWow64FsRedirection",
            "Wow64RevertWow64FsRedirection",
            "Wow64EnableWow64FsRedirection",
            "GetProcessHeap",
            "HeapCreate",
            "HeapAlloc",
            "HeapFree",
            "HeapWalk",
            "GlobalAlloc",
            "GlobalLock",
            "LocalAlloc",
            "VirtualQuery",
            "VirtualQueryEx",
            "FlushInstructionCache",
            "GetWriteWatch",
            "ResetWriteWatch",
            "SetFileAttributesW",
            "DeleteFileTransactedA",
            "CreateTransaction",
            "CommitTransaction",
            "RollbackTransaction",
            "NtCreateTransaction",
            "SetProcessDEPPolicy",
            "GetEnvironmentVariableA",
            "GetEnvironmentVariableW",
            "SetEnvironmentVariableA",
            "GetEnvironmentStringsA",
            "CreateDesktopA",
            "SwitchDesktop",
            "SetThreadDesktop",
            "OpenDesktopA",
            "SetErrorMode",
            "SetThreadErrorMode",
            "EventWrite",
            "EtwEventWrite",
            "EtwEventRegister",
            "EtwEventUnregister",
            "AmsiScanBuffer",
            "AmsiInitialize",
            "AmsiOpenSession",
            "SaferComputeTokenFromLevel",
            "SaferCreateLevel",
            "GetModuleHandleExW",
            "EnumSystemFirmwareTables",
            "GetSystemFirmwareTable",
            "SetupDiGetClassDevsA",
            "SetupDiEnumDeviceInfo",
            "RtlDecompressBuffer",
            "RtlCompressBuffer",
        ],
    ),
    "credential": (
        HIGH,
        [
            "CredEnumerateA",
            "CredEnumerateW",
            "CredReadA",
            "CredReadW",
            "CredWriteA",
            "CredFree",
            "CredDeleteA",
            "LsaOpenPolicy",
            "LsaRetrievePrivateData",
            "LsaEnumerateLogonSessions",
            "LsaGetLogonSessionData",
            "LsaCallAuthenticationPackage",
            "SamConnect",
            "SamEnumerateDomainsInSamServer",
            "SamLookupDomainInSamServer",
            "MsvpPasswordValidate",
            "SspiPromptForCredentialsA",
            "CredUIPromptForCredentialsA",
            "CredUIPromptForWindowsCredentialsA",
            "NetUserChangePassword",
            "WNetGetUserA",
            "SqliteOpen",
            "sqlite3_open",
            "sqlite3_prepare_v2",
            "sqlite3_step",
        ],
    ),
}


# ---------------------------------------------------------------------------
# API → ATT&CK
# ---------------------------------------------------------------------------
# ``min_apis`` is the field the equivalent public tables lack, and it is what
# separates a usable layer from a firehose. A rule of "any match counts" turns a
# lone GetUserNameA into an Account Discovery finding; requiring two distinct
# imports means the claim describes a capability, not a coincidence.
#
# ``confidence_max`` never exceeds 0.65 — below the YARA floor of 0.70 — so a
# deterministic import signal corroborates other layers without solo-driving a
# verdict. That ceiling is enforced again in the loader.

ATTCK_TECHNIQUES: list[dict[str, Any]] = [
    # ---------------------------------------------------------------- Discovery
    {
        "technique_id": "T1057",
        "name": "Process Discovery",
        "min_apis": 2,
        "confidence_base": 0.42,
        "confidence_max": 0.62,
        "apis": [
            "CreateToolhelp32Snapshot",
            "Process32First",
            "Process32FirstW",
            "Process32Next",
            "Process32NextW",
            "EnumProcesses",
            "EnumProcessModules",
            "GetProcessImageFileNameA",
            "QueryFullProcessImageNameA",
        ],
    },
    {
        "technique_id": "T1082",
        "name": "System Information Discovery",
        "min_apis": 3,
        "confidence_base": 0.40,
        "confidence_max": 0.58,
        "apis": [
            "GetSystemInfo",
            "GetNativeSystemInfo",
            "GetVersionExA",
            "GetVersionExW",
            "GetComputerNameA",
            "GetComputerNameW",
            "GlobalMemoryStatusEx",
            "GetSystemMetrics",
            "GetProductInfo",
            "GetCurrentHwProfileA",
            "GetSystemFirmwareTable",
            "GetLogicalDrives",
            "GetVolumeInformationA",
        ],
    },
    {
        "technique_id": "T1033",
        "name": "System Owner/User Discovery",
        "min_apis": 2,
        "confidence_base": 0.42,
        "confidence_max": 0.60,
        "apis": [
            "GetUserNameA",
            "GetUserNameW",
            "GetUserNameExA",
            "LookupAccountSidA",
            "LookupAccountNameA",
            "NetUserGetInfo",
            "WTSQuerySessionInformationA",
        ],
    },
    {
        "technique_id": "T1087",
        "name": "Account Discovery",
        "min_apis": 2,
        "confidence_base": 0.44,
        "confidence_max": 0.62,
        "apis": [
            "NetUserEnum",
            "NetLocalGroupGetMembers",
            "NetUserGetInfo",
            "LookupAccountNameA",
            "CheckTokenMembership",
            "DsGetDcNameA",
        ],
    },
    {
        "technique_id": "T1012",
        "name": "Query Registry",
        "min_apis": 2,
        "confidence_base": 0.38,
        "confidence_max": 0.55,
        "apis": [
            "RegQueryValueExA",
            "RegQueryValueExW",
            "RegQueryInfoKeyA",
            "RegEnumKeyExA",
            "RegEnumValueA",
            "RegGetValueA",
            "SHGetValueA",
            "NtQueryValueKey",
            "NtEnumerateKey",
        ],
    },
    {
        "technique_id": "T1083",
        "name": "File and Directory Discovery",
        "min_apis": 3,
        "confidence_base": 0.38,
        "confidence_max": 0.55,
        "apis": [
            "FindFirstFileA",
            "FindFirstFileW",
            "FindNextFileA",
            "FindNextFileW",
            "GetFileAttributesA",
            "GetLogicalDriveStringsA",
            "GetDriveTypeA",
            "PathFileExistsA",
            "SHGetFolderPathA",
        ],
    },
    {
        "technique_id": "T1010",
        "name": "Application Window Discovery",
        "min_apis": 2,
        "confidence_base": 0.44,
        "confidence_max": 0.60,
        "apis": [
            "EnumWindows",
            "FindWindowA",
            "FindWindowW",
            "GetWindowTextA",
            "GetWindowTextW",
            "GetForegroundWindow",
            "GetClassNameA",
            "EnumDesktopWindows",
        ],
    },
    {
        "technique_id": "T1016",
        "name": "System Network Configuration Discovery",
        "min_apis": 2,
        "confidence_base": 0.42,
        "confidence_max": 0.58,
        "apis": [
            "GetAdaptersInfo",
            "GetAdaptersAddresses",
            "GetIfTable",
            "gethostname",
            "GetNetworkParams",
            "SendARP",
            "NetWkstaGetInfo",
        ],
    },
    {
        "technique_id": "T1049",
        "name": "System Network Connections Discovery",
        "min_apis": 2,
        "confidence_base": 0.44,
        "confidence_max": 0.60,
        "apis": [
            "GetTcpTable",
            "GetExtendedTcpTable",
            "GetUdpTable",
            "NetShareEnum",
            "WNetOpenEnumA",
            "WNetEnumResourceA",
            "NetServerEnum",
        ],
    },
    {
        "technique_id": "T1007",
        "name": "System Service Discovery",
        "min_apis": 2,
        "confidence_base": 0.44,
        "confidence_max": 0.60,
        "apis": [
            "EnumServicesStatusA",
            "EnumServicesStatusExA",
            "QueryServiceConfigA",
            "EnumDependentServicesA",
            "OpenSCManagerA",
        ],
    },
    {
        "technique_id": "T1614",
        "name": "System Location Discovery",
        "min_apis": 2,
        "confidence_base": 0.44,
        "confidence_max": 0.58,
        "apis": [
            "GetLocaleInfoA",
            "GetLocaleInfoW",
            "GetSystemDefaultLangID",
            "GetUserDefaultLangID",
            "GetUserDefaultUILanguage",
            "GetTimeZoneInformation",
            "GetKeyboardLayout",
            "EnumSystemLocalesA",
        ],
    },
    # ------------------------------------------------------------- Persistence
    {
        "technique_id": "T1543.003",
        "name": "Create or Modify System Process: Windows Service",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": [
            "CreateServiceA",
            "CreateServiceW",
            "OpenSCManagerA",
            "OpenSCManagerW",
            "StartServiceA",
            "ChangeServiceConfigA",
            "ChangeServiceConfig2A",
            "DeleteService",
            "ControlService",
        ],
    },
    {
        "technique_id": "T1547.001",
        "name": "Boot or Logon Autostart Execution: Registry Run Keys",
        "min_apis": 2,
        "confidence_base": 0.42,
        "confidence_max": 0.60,
        "apis": [
            "RegCreateKeyExA",
            "RegCreateKeyExW",
            "RegSetValueExA",
            "RegSetValueExW",
            "SHSetValueA",
            "NtSetValueKey",
        ],
    },
    {
        "technique_id": "T1053.005",
        "name": "Scheduled Task/Job: Scheduled Task",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": [
            "NetScheduleJobAdd",
            "NetScheduleJobEnum",
            "ITaskScheduler",
            "ITaskService",
            "IRegisteredTask",
            "ITaskFolder",
        ],
    },
    {
        "technique_id": "T1546.003",
        "name": "Event Triggered Execution: WMI Event Subscription",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": ["IWbemLocator", "IWbemServices", "IWbemClassObject", "CoSetProxyBlanket"],
    },
    # --------------------------------------------------------- Privilege Esc.
    {
        "technique_id": "T1134",
        "name": "Access Token Manipulation",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": [
            "OpenProcessToken",
            "OpenThreadToken",
            "AdjustTokenPrivileges",
            "DuplicateTokenEx",
            "DuplicateToken",
            "SetThreadToken",
            "ImpersonateLoggedOnUser",
            "CreateProcessWithTokenW",
            "CreateProcessAsUserA",
            "SetTokenInformation",
            "RtlAdjustPrivilege",
            "NtAdjustPrivilegesToken",
            "ImpersonateNamedPipeClient",
        ],
    },
    {
        "technique_id": "T1548.002",
        "name": "Abuse Elevation Control Mechanism: Bypass UAC",
        "min_apis": 2,
        "confidence_base": 0.45,
        "confidence_max": 0.62,
        "apis": [
            "ShellExecuteExA",
            "ShellExecuteExW",
            "CoGetObject",
            "CLSIDFromProgID",
            "CheckTokenMembership",
            "GetTokenInformation",
        ],
    },
    # ------------------------------------------------------- Defense Evasion
    {
        "technique_id": "T1055",
        "name": "Process Injection",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": [
            "WriteProcessMemory",
            "VirtualAllocEx",
            "CreateRemoteThread",
            "CreateRemoteThreadEx",
            "NtCreateThreadEx",
            "RtlCreateUserThread",
            "QueueUserAPC",
            "NtQueueApcThread",
            "SetWindowsHookEx",
            "NtWriteVirtualMemory",
            "NtAllocateVirtualMemory",
            "OpenProcess",
        ],
    },
    {
        "technique_id": "T1055.012",
        "name": "Process Injection: Process Hollowing",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": [
            "NtUnmapViewOfSection",
            "ZwUnmapViewOfSection",
            "SetThreadContext",
            "GetThreadContext",
            "ResumeThread",
            "WriteProcessMemory",
            "CreateProcessInternalW",
        ],
    },
    {
        "technique_id": "T1620",
        "name": "Reflective Code Loading",
        "min_apis": 2,
        "confidence_base": 0.45,
        "confidence_max": 0.62,
        "apis": [
            "NtCreateSection",
            "ZwCreateSection",
            "NtMapViewOfSection",
            "MapViewOfFile",
            "CreateFileMappingA",
            "LdrLoadDll",
            "LdrGetProcedureAddress",
        ],
    },
    {
        "technique_id": "T1622",
        "name": "Debugger Evasion",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": [
            "IsDebuggerPresent",
            "CheckRemoteDebuggerPresent",
            "NtQueryInformationProcess",
            "NtSetInformationThread",
            "OutputDebugStringA",
            "DebugActiveProcess",
            "NtClose",
        ],
    },
    {
        "technique_id": "T1497",
        "name": "Virtualization/Sandbox Evasion",
        "min_apis": 2,
        "confidence_base": 0.42,
        "confidence_max": 0.60,
        "apis": [
            "GetSystemFirmwareTable",
            "EnumSystemFirmwareTables",
            "SetupDiGetClassDevsA",
            "SetupDiEnumDeviceInfo",
            "GetLastInputInfo",
            "GetCursorPos",
            "IsProcessorFeaturePresent",
        ],
    },
    {
        "technique_id": "T1497.003",
        "name": "Virtualization/Sandbox Evasion: Time Based Evasion",
        "min_apis": 3,
        "confidence_base": 0.40,
        "confidence_max": 0.58,
        "apis": [
            "GetTickCount",
            "GetTickCount64",
            "QueryPerformanceCounter",
            "QueryPerformanceFrequency",
            "GetSystemTimeAsFileTime",
            "timeGetTime",
            "NtQueryPerformanceCounter",
            "NtYieldExecution",
        ],
    },
    {
        "technique_id": "T1112",
        "name": "Modify Registry",
        "min_apis": 2,
        "confidence_base": 0.40,
        "confidence_max": 0.58,
        "apis": [
            "RegSetValueExA",
            "RegSetValueExW",
            "RegCreateKeyExA",
            "RegDeleteValueA",
            "RegDeleteKeyA",
            "RegDeleteTreeA",
            "NtSetValueKey",
            "NtDeleteKey",
            "RegRestoreKeyA",
            "RegLoadKeyA",
        ],
    },
    {
        "technique_id": "T1562.001",
        "name": "Impair Defenses: Disable or Modify Tools",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": [
            "AmsiScanBuffer",
            "AmsiInitialize",
            "AmsiOpenSession",
            "EtwEventWrite",
            "EtwEventRegister",
            "EtwEventUnregister",
            "EventWrite",
        ],
    },
    {
        "technique_id": "T1562.006",
        "name": "Impair Defenses: Indicator Blocking",
        "min_apis": 2,
        "confidence_base": 0.46,
        "confidence_max": 0.62,
        "apis": ["EtwEventUnregister", "EtwEventRegister", "EventWrite", "ReportEventA"],
    },
    {
        "technique_id": "T1070.004",
        "name": "Indicator Removal: File Deletion",
        "min_apis": 2,
        "confidence_base": 0.38,
        "confidence_max": 0.55,
        "apis": [
            "DeleteFileA",
            "DeleteFileW",
            "SHFileOperationA",
            "MoveFileExA",
            "DeleteFileTransactedA",
            "NtDeleteFile",
        ],
    },
    {
        "technique_id": "T1070.006",
        "name": "Indicator Removal: Timestomp",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": ["SetFileTime", "GetFileTime", "NtSetInformationFile"],
    },
    {
        # VirtualProtect deliberately absent. It is in every packer *and* in
        # every JIT, every hot-patcher and much of the CRT, so including it
        # would make this rule fire on ordinary software — and this particular
        # technique is one the local model already over-claims, which is why
        # capability_matrix caps it. Feeding that cap a noisy signal would be
        # worse than leaving the rule out.
        "technique_id": "T1027",
        "name": "Obfuscated Files or Information",
        "min_apis": 2,
        "confidence_base": 0.40,
        "confidence_max": 0.58,
        "apis": [
            "CryptStringToBinaryA",
            "CryptBinaryToStringA",
            "RtlDecompressBuffer",
            "RtlCompressBuffer",
        ],
    },
    {
        "technique_id": "T1140",
        "name": "Deobfuscate/Decode Files or Information",
        "min_apis": 2,
        "confidence_base": 0.40,
        "confidence_max": 0.58,
        "apis": [
            "CryptStringToBinaryA",
            "CryptUnprotectData",
            "RtlDecompressBuffer",
            "CryptDecrypt",
            "BCryptDecrypt",
            "SystemFunction036",
        ],
    },
    # T1036 (Masquerading) and T1218 (System Binary Proxy Execution) are
    # deliberately absent. Masquerading is a property of a file's *name and
    # appearance*, which an import table cannot see — SetFileAttributes and
    # CopyFile are the wrong evidence for it. Proxy execution needs the command
    # line, which the LOLBin layer already reads from sandbox telemetry;
    # inferring it from "this binary can start a process" would fire on nearly
    # everything and add nothing the LOLBin layer does not do properly.
    {
        "technique_id": "T1564.003",
        "name": "Hide Artifacts: Hidden Window",
        "min_apis": 2,
        "confidence_base": 0.44,
        "confidence_max": 0.60,
        "apis": [
            "CreateDesktopA",
            "SwitchDesktop",
            "SetThreadDesktop",
            "OpenDesktopA",
            "IsWindowVisible",
        ],
    },
    # ----------------------------------------------------- Credential Access
    {
        "technique_id": "T1056.001",
        "name": "Input Capture: Keylogging",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": [
            "GetAsyncKeyState",
            "GetKeyState",
            "GetKeyboardState",
            "RegisterRawInputDevices",
            "GetRawInputData",
            "SetWindowsHookExA",
            "SetWindowsHookExW",
            "AttachThreadInput",
            "MapVirtualKeyA",
            "ToUnicodeEx",
            "GetKeyNameTextA",
            "SetWinEventHook",
        ],
    },
    {
        "technique_id": "T1555",
        "name": "Credentials from Password Stores",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": [
            "CryptUnprotectData",
            "CredEnumerateA",
            "CredEnumerateW",
            "CredReadA",
            "CredReadW",
            "CredFree",
            "CertOpenSystemStoreA",
            "PFXImportCertStore",
            "SystemFunction036",
            "sqlite3_open",
            "sqlite3_prepare_v2",
        ],
    },
    {
        "technique_id": "T1003",
        "name": "OS Credential Dumping",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": [
            "LsaOpenPolicy",
            "LsaRetrievePrivateData",
            "LsaEnumerateLogonSessions",
            "LsaGetLogonSessionData",
            "LsaCallAuthenticationPackage",
            "SamConnect",
            "SamEnumerateDomainsInSamServer",
            "MsvpPasswordValidate",
        ],
    },
    {
        "technique_id": "T1040",
        "name": "Network Sniffing",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": ["WSAIoctl", "ioctlsocket", "bind", "WSASocketA", "recvfrom"],
    },
    # --------------------------------------------------------------- Collection
    {
        "technique_id": "T1113",
        "name": "Screen Capture",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": [
            "BitBlt",
            "StretchBlt",
            "CreateCompatibleBitmap",
            "CreateCompatibleDC",
            "GetDC",
            "GetWindowDC",
            "GetDIBits",
            "PrintWindow",
        ],
    },
    {
        "technique_id": "T1115",
        "name": "Clipboard Data",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": [
            "OpenClipboard",
            "GetClipboardData",
            "SetClipboardData",
            "CloseClipboard",
            "IsClipboardFormatAvailable",
            "AddClipboardFormatListener",
        ],
    },
    {
        "technique_id": "T1123",
        "name": "Audio Capture",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": ["waveInOpen", "waveInStart", "capCreateCaptureWindowA"],
    },
    # ------------------------------------------------------- Command & Control
    {
        "technique_id": "T1071.001",
        "name": "Application Layer Protocol: Web Protocols",
        "min_apis": 2,
        "confidence_base": 0.44,
        "confidence_max": 0.62,
        "apis": [
            "InternetOpenA",
            "InternetOpenW",
            "InternetConnectA",
            "InternetOpenUrlA",
            "InternetReadFile",
            "HttpOpenRequestA",
            "HttpSendRequestA",
            "HttpQueryInfoA",
            "WinHttpOpen",
            "WinHttpConnect",
            "WinHttpOpenRequest",
            "WinHttpSendRequest",
            "WinHttpReceiveResponse",
            "WinHttpReadData",
            "URLDownloadToFileA",
            "URLDownloadToFileW",
        ],
    },
    {
        "technique_id": "T1071.004",
        "name": "Application Layer Protocol: DNS",
        "min_apis": 2,
        "confidence_base": 0.46,
        "confidence_max": 0.62,
        "apis": ["DnsQuery_A", "DnsQuery_W", "DnsQueryEx", "DnsFree", "getaddrinfo"],
    },
    {
        "technique_id": "T1095",
        "name": "Non-Application Layer Protocol",
        "min_apis": 3,
        "confidence_base": 0.40,
        "confidence_max": 0.58,
        "apis": [
            "socket",
            "connect",
            "send",
            "recv",
            "WSASocketA",
            "WSAConnect",
            "WSASend",
            "WSARecv",
            "sendto",
            "recvfrom",
            "IcmpSendEcho",
        ],
    },
    {
        "technique_id": "T1105",
        "name": "Ingress Tool Transfer",
        "min_apis": 2,
        "confidence_base": 0.46,
        "confidence_max": 0.62,
        "apis": [
            "URLDownloadToFileA",
            "URLDownloadToFileW",
            "URLDownloadToCacheFileA",
            "InternetReadFile",
            "WinHttpReadData",
            "FtpGetFileA",
        ],
    },
    # ------------------------------------------------------------------ Impact
    {
        "technique_id": "T1486",
        "name": "Data Encrypted for Impact",
        "min_apis": 2,
        "confidence_base": 0.48,
        "confidence_max": 0.65,
        "apis": [
            "CryptEncrypt",
            "BCryptEncrypt",
            "CryptGenKey",
            "CryptDeriveKey",
            "BCryptGenerateSymmetricKey",
            "CryptAcquireContextA",
            "NCryptEncrypt",
            "BCryptDeriveKeyPBKDF2",
        ],
    },
    {
        "technique_id": "T1490",
        "name": "Inhibit System Recovery",
        "min_apis": 2,
        "confidence_base": 0.50,
        "confidence_max": 0.65,
        "apis": ["DeleteFileA", "SHFileOperationA", "ControlService", "DeleteService"],
    },
    {
        "technique_id": "T1489",
        "name": "Service Stop",
        "min_apis": 2,
        "confidence_base": 0.46,
        "confidence_max": 0.62,
        "apis": ["ControlService", "OpenServiceA", "DeleteService", "TerminateProcess"],
    },
    # ---------------------------------------------------------------- Execution
    {
        "technique_id": "T1106",
        "name": "Native API",
        "min_apis": 3,
        "confidence_base": 0.38,
        "confidence_max": 0.55,
        "apis": [
            "NtCreateUserProcess",
            "NtCreateFile",
            "NtWriteFile",
            "NtOpenKey",
            "NtSetValueKey",
            "NtQuerySystemInformation",
            "NtAllocateVirtualMemory",
            "NtProtectVirtualMemory",
            "LdrLoadDll",
            "RtlCreateProcessParameters",
        ],
    },
    # T1129 (Shared Modules) is deliberately absent for the same reason, only
    # more so: LoadLibrary + GetProcAddress appear in essentially every PE ever
    # compiled, so a rule keyed on them fires always and therefore carries zero
    # information. What *is* suspicious is that pair in a binary with almost no
    # other imports — dynamic API resolution — and that is already detected, as
    # an obfuscation indicator, by ``_pe_obfuscation_indicators``.
]

_CONFIDENCE_CEILING = 0.65


def _validate() -> list[str]:
    """Return a list of problems; empty means the tables are internally sound."""
    problems: list[str] = []

    # Every ATT&CK id must exist in the vendored catalog.
    try:
        valid_raw = json.loads(_VALID_IDS.read_text(encoding="utf-8"))
        valid_ids = set(
            valid_raw if isinstance(valid_raw, list) else valid_raw.get("technique_ids", [])
        )
    except (OSError, ValueError) as exc:
        problems.append(f"cannot read {_VALID_IDS}: {exc}")
        valid_ids = set()

    known_apis = {api for _tier, apis in WINDOWS_CATEGORIES.values() for api in apis}

    for tech in ATTCK_TECHNIQUES:
        tid = tech["technique_id"]
        if valid_ids and tid not in valid_ids:
            problems.append(f"{tid} is not in attck_valid_ids.json")
        if tech["confidence_max"] > _CONFIDENCE_CEILING:
            problems.append(f"{tid} confidence_max {tech['confidence_max']} exceeds ceiling")
        if tech["confidence_base"] > tech["confidence_max"]:
            problems.append(f"{tid} confidence_base above confidence_max")
        if tech["min_apis"] > len(tech["apis"]):
            problems.append(f"{tid} min_apis exceeds its own api list")
        # An ATT&CK entry naming an API the behaviour table has never heard of is
        # almost always a typo, and a typo here is silent: the technique simply
        # never fires.
        for api in tech["apis"]:
            if api not in known_apis:
                problems.append(f"{tid} references unknown API {api!r}")

    seen: set[str] = set()
    for tid in (t["technique_id"] for t in ATTCK_TECHNIQUES):
        if tid in seen:
            problems.append(f"duplicate technique {tid}")
        seen.add(tid)

    return problems


def main() -> int:
    problems = _validate()
    if problems:
        for p in problems:
            print(f"ERROR: {p}", file=sys.stderr)
        return 1

    behaviour = {
        "schema": "maljan-api-behaviour/v1",
        "version": "1.0",
        "platforms": {
            "windows": {
                cat: {"tier": tier, "apis": sorted(set(apis))}
                for cat, (tier, apis) in WINDOWS_CATEGORIES.items()
            }
        },
    }
    attck = {
        "schema": "maljan-api-attck/v1",
        "version": "1.0",
        "techniques": [
            {**t, "platforms": ["windows"], "apis": sorted(set(t["apis"]))}
            for t in ATTCK_TECHNIQUES
        ],
    }

    _BEHAVIOUR_OUT.write_text(json.dumps(behaviour, indent=2) + "\n", encoding="utf-8")
    _ATTCK_OUT.write_text(json.dumps(attck, indent=2) + "\n", encoding="utf-8")

    total_apis = sum(len(set(apis)) for _tier, apis in WINDOWS_CATEGORIES.values())
    print(
        f"wrote {_BEHAVIOUR_OUT.relative_to(_ROOT)}: "
        f"{len(WINDOWS_CATEGORIES)} categories, {total_apis} APIs"
    )
    print(f"wrote {_ATTCK_OUT.relative_to(_ROOT)}: {len(ATTCK_TECHNIQUES)} techniques")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
